In [1]:
import aiohttp
import asyncio
import nest_asyncio
import os
from dotenv import load_dotenv
from typing import List, Dict, Any, Tuple, Union
import json
from github import Github, Auth
from gidgethub.aiohttp import GitHubAPI
from gidgethub import GitHubException
import sys
import base64
from stamina import retry, retry_context
import re
from functools import partial
from textacy import preprocessing
from langchain_qdrant import QdrantVectorStore
from qdrant_client import QdrantClient
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings
from qdrant_client.http.models import Distance, VectorParams
import uuid
from searcharray import SearchArray
from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate
from langgraph.graph import START, StateGraph
from langchain_core.documents import Document
from typing_extensions import List, TypedDict
from langchain_community.retrievers import BM25Retriever
from langchain.retrievers import EnsembleRetriever
from langchain_cohere import CohereRerank
from langchain.retrievers.contextual_compression import ContextualCompressionRetriever

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# allow for multiple event loops within Jupyter
nest_asyncio.apply()

# load environment variables
load_dotenv()

import pickle

In [2]:
MAX_CHARACTERS = 30_000
NAMESPACE = uuid.NAMESPACE_URL

def strip_markdown(text: str) -> str:
    """Remove common Markdown syntax; keep inner text and emojis."""
    # Headings: ## Title -> Title
    text = re.sub(r"^#{1,6}\s*", "", text, flags=re.MULTILINE)
    # Inline code: `code` -> code
    text = re.sub(r"`([^`]+)`", r"\1", text)
    # Bold/italic: **bold** or *italic* -> bold / italic
    text = re.sub(r"\*{1,2}([^*]+)\*{1,2}", r"\1", text)
    text = re.sub(r"_{1,2}([^_]+)_{1,2}", r"\1", text)
    # Link markup: [text](url) -> text
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    # Collapse many newlines
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def make_normalize_text_pipeline(
    *,
    url_repl: str = "",
    unicode_form: str = "NFC",
):
    """
    Build a textacy pipeline: Markdown/HTML → plain text (emojis kept).

    Args:
        url_repl: Replacement for URLs (default ""). Use "_URL_" to keep a placeholder.
        unicode_form: Unicode normalization form ("NFC", "NFD", "NFKC", "NFKD"). Default "NFC".

    Returns:
        A callable that takes a string and returns preprocessed plain text.
    """
    return preprocessing.make_pipeline(
        strip_markdown,
        preprocessing.remove.html_tags,
        preprocessing.normalize.bullet_points,
        preprocessing.normalize.quotation_marks,
        partial(preprocessing.normalize.unicode, form=unicode_form),
        preprocessing.normalize.whitespace,
    )


# Default pipeline instance
normalize_text_pipeline = make_normalize_text_pipeline()

def repo_to_uuid(repo_name: str) -> str:
    return str(uuid.uuid5(NAMESPACE, repo_name))

def normalize_docs(docs: List[Dict[str, Any]]):
    content_str = ''
    for doc in docs:
        content_str += (doc['content'] + '\n\n')
    truncated = content_str[:MAX_CHARACTERS] if len(content_str) > MAX_CHARACTERS else content_str
    normalized_text = normalize_text_pipeline(truncated)
    return normalized_text


def organize_repo_data(repo_data: List[Dict[Any, Any]]) -> Tuple[List[str], List[Dict[str, Union[str, int]]], List[str]]:
    ids = []
    metadata = []
    docs = []
    for repo in repo_data:
        id = repo_to_uuid(repo['repo'])
        description = repo['description']
        topics = repo['topics']
        doc_source = repo['doc_source']
        stars = repo['stars']
        url = repo['url']
        language = repo['language']
        # append to lists for DB consumption
        ids.append(id)
        metadata.append({
            'id': id,
            'repo': repo['repo'],
            'description': description,
            'topics': topics,
            'language': language,
            'doc_source': doc_source,
            'stars': stars,
            'url': url,
        })
        topics_str = f"Topics: {','.join(topics)}\n"
        docs.append(topics_str + normalize_docs(repo['docs']))
    return ids, metadata, docs


def preprocess_text(text: str | None) -> List[str]:
    """borrowed from Ask Brave search for common preprocessing/tokenizer steps before TF-IDF"""
    if text is None:
        return []
    # Lowercase
    text = text.lower()
    # Remove punctuation and digits
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    # Tokenize
    tokens = word_tokenize(text)
    # Remove stopwords and short words
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words and len(word) > 2]
    # Lemmatize
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return tokens

In [3]:
# load cached github data
with open("../data/cached/github_data.pkl", "rb") as f:
    starred_repo_data = pickle.load(f)

In [4]:
ids, metadata, docs = organize_repo_data(starred_repo_data)

In [5]:
metadata[0]

{'id': 'a5ef9890-4c52-5a83-8aa1-c1b266a4f6fb',
 'repo': 'pymc-devs/pytensor',
 'description': 'PyTensor allows you to define, optimize, and efficiently evaluate mathematical expressions involving multi-dimensional arrays.',
 'topics': ['ai',
  'bayesian-inference',
  'computational-science',
  'deep-learning',
  'statistics'],
 'language': 'Python',
 'doc_source': 'readme',
 'stars': 594,
 'url': 'https://github.com/pymc-devs/pytensor'}

In [6]:
docs[0]

'Topics: ai,bayesian-inference,computational-science,deep-learning,statistics\n.. image:: https://cdn.rawgit.com/pymc-devs/pytensor/main/doc/images/PyTensorRGB.svg\n :height: 100px\n :alt: PyTensor logo\n :align: center\n|Tests Status| |Coverage|\n|Project Name| is a Python library that allows one to define, optimize, and\nefficiently evaluate mathematical expressions involving multi-dimensional arrays.\nIt provides the computational backend for PyMC .\nFeatures\n========\n- A hackable, pure-Python codebase\n- Extensible graph framework suitable for rapid development of custom operators and symbolic optimizations\n- Implements an extensible graph transpilation framework that currently provides\n compilation via C, JAX , and Numba \n- Contrary to PyTorch and TensorFlow, PyTensor maintains a static graph which can be modified in-place to\n allow for advanced optimizations\nGetting started\n===============\n.. code-block:: python\n import pytensor\n from pytensor import tensor as pt\n # Declare two symbolic floating-point scalars\n a = pt.dscalar("a")\n b = pt.dscalar("b")\n # Create a simple example expression\n c = a + b\n # Convert the expression into a callable object that takes (a, b)\n # values as input and computes the value of c.\n fc = pytensor.function([a, b], c)\n assert fc(1.5, 2.5) == 4.0\n # Compute the gradient of the example expression with respect to a\n dc = pytensor.grad(c, a)\n fdc = pytensor.function([a, b], dc)\n assert fdc(1.5, 2.5) == 1.0\n # Compiling functions with pytensor.function also optimizes\n # expression graphs by removing unnecessary operations and\n # replacing computations with more efficient ones.\n v = pt.vector("v")\n M = pt.matrix("M")\n d = a/a + (M + a).dot(v)\n pytensor.dprint(d)\n # Add [id A]\n # ├─ ExpandDims{axis=0} [id B]\n # │ └─ Truediv [id C]\n # │ ├─ a [id D]\n # │ └─ a [id D]\n # └─ dot [id E]\n # ├─ Add [id F]\n # │ ├─ M [id G]\n # │ └─ ExpandDims{axes=[0, 1]} [id H]\n # │ └─ a [id D]\n # └─ v [id I]\n fd = pytensor.function([a, v, M], d)\n # a/a -> 1 and the dot product is replaced with a BLAS function\n # (i.e. CGemv)\n pytensor.dprint(fd)\n # Add [id A] 5\n # ├─ [1.] [id B]\n # └─ CGemv{inplace} [id C] 4\n # ├─ AllocEmpty{dtype=\'float64\'} [id D] 3\n # │ └─ Shapei{0} [id E] 2\n # │ └─ M [id F]\n # ├─ 1.0 [id G]\n # ├─ Add [id H] 1\n # │ ├─ M [id F]\n # │ └─ ExpandDims{axes=[0, 1]} [id I] 0\n # │ └─ a [id J]\n # ├─ v [id K]\n # └─ 0.0 [id L]\nSee the PyTensor documentation for in-depth tutorials.\nInstallation\n============\nThe latest release of |Project Name| can be installed from PyPI using \'pip:\n::\n pip install pytensor\nOr via conda-forge:\n::\n conda install -c conda-forge pytensor\nThe current development branch of |Project Name| can be installed from GitHub, also using pip:\n::\n pip install git+https://github.com/pymc-devs/pytensor\nBackground\n==========\nPyTensor is a fork of Aesara , which is a fork of Theano .\nContributing\n============\nWe welcome bug reports and fixes and improvements to the documentation.\nFor more information on contributing, please see the\ncontributing guide .\nA good place to start contributing is by looking through the issues\nhere \'__.\n.. |Project Name| replace:: PyTensor\n.. |Tests Status| image:: https://github.com/pymc-devs/pytensor/workflows/Tests/badge.svg\n :target: https://github.com/pymc-devs/pytensor/actions?query=workflow%3ATests+branch%3Amain\n.. |Coverage| image:: https://codecov.io/gh/pymc-devs/pytensor/branch/main/graph/badge.svg?token=WVwr8nZYmc\n :target: https://codecov.io/gh/pymc-devs/pytensor'

In [7]:
starred_repo_data[0]

{'repo': 'pymc-devs/pytensor',
 'description': 'PyTensor allows you to define, optimize, and efficiently evaluate mathematical expressions involving multi-dimensional arrays.',
 'topics': ['ai',
  'bayesian-inference',
  'computational-science',
  'deep-learning',
  'statistics'],
 'stars': 594,
 'language': 'Python',
 'url': 'https://github.com/pymc-devs/pytensor',
 'doc_source': 'readme',
 'docs': [{'name': 'README.rst',
   'path': 'README.rst',
   'size': 4199,
   'content': '.. image:: https://cdn.rawgit.com/pymc-devs/pytensor/main/doc/images/PyTensor_RGB.svg\n    :height: 100px\n    :alt: PyTensor logo\n    :align: center\n\n|Tests Status| |Coverage|\n\n|Project Name| is a Python library that allows one to define, optimize, and\nefficiently evaluate mathematical expressions involving multi-dimensional arrays.\nIt provides the computational backend for `PyMC <https://github.com/pymc-devs/pymc>`__.\n\nFeatures\n========\n\n- A hackable, pure-Python codebase\n- Extensible graph framework suitable for rapid development of custom operators and symbolic optimizations\n- Implements an extensible graph transpilation framework that currently provides\n  compilation via C, `JAX <https://github.com/google/jax>`__, and `Numba <https://github.com/numba/numba>`__\n- Contrary to PyTorch and TensorFlow, PyTensor maintains a static graph which can be modified in-place to\n  allow for advanced optimizations\n\nGetting started\n===============\n\n.. code-block:: python\n\n    import pytensor\n    from pytensor import tensor as pt\n\n    # Declare two symbolic floating-point scalars\n    a = pt.dscalar("a")\n    b = pt.dscalar("b")\n\n    # Create a simple example expression\n    c = a + b\n\n    # Convert the expression into a callable object that takes `(a, b)`\n    # values as input and computes the value of `c`.\n    f_c = pytensor.function([a, b], c)\n\n    assert f_c(1.5, 2.5) == 4.0\n\n    # Compute the gradient of the example expression with respect to `a`\n    dc = pytensor.grad(c, a)\n\n    f_dc = pytensor.function([a, b], dc)\n\n    assert f_dc(1.5, 2.5) == 1.0\n\n    # Compiling functions with `pytensor.function` also optimizes\n    # expression graphs by removing unnecessary operations and\n    # replacing computations with more efficient ones.\n\n    v = pt.vector("v")\n    M = pt.matrix("M")\n\n    d = a/a + (M + a).dot(v)\n\n    pytensor.dprint(d)\n    #  Add [id A]\n    #  ├─ ExpandDims{axis=0} [id B]\n    #  │  └─ True_div [id C]\n    #  │     ├─ a [id D]\n    #  │     └─ a [id D]\n    #  └─ dot [id E]\n    #     ├─ Add [id F]\n    #     │  ├─ M [id G]\n    #     │  └─ ExpandDims{axes=[0, 1]} [id H]\n    #     │     └─ a [id D]\n    #     └─ v [id I]\n\n    f_d = pytensor.function([a, v, M], d)\n\n    # `a/a` -> `1` and the dot product is replaced with a BLAS function\n    # (i.e. CGemv)\n    pytensor.dprint(f_d)\n    # Add [id A] 5\n    #  ├─ [1.] [id B]\n    #  └─ CGemv{inplace} [id C] 4\n    #     ├─ AllocEmpty{dtype=\'float64\'} [id D] 3\n    #     │  └─ Shape_i{0} [id E] 2\n    #     │     └─ M [id F]\n    #     ├─ 1.0 [id G]\n    #     ├─ Add [id H] 1\n    #     │  ├─ M [id F]\n    #     │  └─ ExpandDims{axes=[0, 1]} [id I] 0\n    #     │     └─ a [id J]\n    #     ├─ v [id K]\n    #     └─ 0.0 [id L]\n\nSee `the PyTensor documentation <https://pytensor.readthedocs.io/en/latest/>`__ for in-depth tutorials.\n\n\nInstallation\n============\n\nThe latest release of |Project Name| can be installed from PyPI using ``pip``:\n\n::\n\n    pip install pytensor\n\n\nOr via conda-forge:\n\n::\n\n    conda install -c conda-forge pytensor\n\n\nThe current development branch of |Project Name| can be installed from GitHub, also using ``pip``:\n\n::\n\n    pip install git+https://github.com/pymc-devs/pytensor\n\n\nBackground\n==========\n\nPyTensor is a fork of `Aesara <https://github.com/aesara-devs/aesara>`__, which is a fork of `Theano <https://github.com/Theano/Theano>`__.\n\nContributing\n============\n\nWe welcome bug reports and fixes and improvements to the documentation.\n\nFor more information on contributing, please see the\n`contributing guide <https://pytensor.readthedocs.io/en/latest/dev_start_guide.html>`__.\n\nA good place to start contributing is by looking through the issues\n`here <https://github.com/pymc-devs/pytensor/issues>`__.\n\n\n.. |Project Name| replace:: PyTensor\n.. |Tests Status| image:: https://github.com/pymc-devs/pytensor/workflows/Tests/badge.svg\n  :target: https://github.com/pymc-devs/pytensor/actions?query=workflow%3ATests+branch%3Amain\n.. |Coverage| image:: https://codecov.io/gh/pymc-devs/pytensor/branch/main/graph/badge.svg?token=WVwr8nZYmc\n  :target: https://codecov.io/gh/pymc-devs/pytensor\n'}]}

In [8]:
df = pd.DataFrame(starred_repo_data)
df.head()

,repo,description,topics,stars,language,url,doc_source,docs
0,pymc-devs/pytensor,"PyTensor allows you to define, optimize, and e...","[ai, bayesian-inference, computational-science...",594,Python,https://github.com/pymc-devs/pytensor,readme,"[{'name': 'README.rst', 'path': 'README.rst', ..."
1,Pyomo/pyomo-gallery,A collection of Pyomo examples,[],315,Jupyter Notebook,https://github.com/Pyomo/pyomo-gallery,readme,"[{'name': 'README.md', 'path': 'README.md', 's..."
2,Pyomo/pyomo-tutorials,A modern set of Pyomo tutorials,[],41,Python,https://github.com/Pyomo/pyomo-tutorials,readme,"[{'name': 'README.md', 'path': 'README.md', 's..."
3,norhum/reinforcement-learning-from-scratch,RL for total beginners,[],120,Jupyter Notebook,https://github.com/norhum/reinforcement-learni...,readme,"[{'name': 'README.md', 'path': 'README.md', 's..."
4,deanmalmgren/textract,extract text from any document. no muss. no fuss.,"[data-mining, natural-language-processing, pyt...",4464,HTML,https://github.com/deanmalmgren/textract,readme,"[{'name': 'README.rst', 'path': 'README.rst', ..."

In [9]:
df['id'] = df['repo'].apply(repo_to_uuid)
df.head()

,repo,description,topics,stars,language,url,doc_source,docs,id
0,pymc-devs/pytensor,"PyTensor allows you to define, optimize, and e...","[ai, bayesian-inference, computational-science...",594,Python,https://github.com/pymc-devs/pytensor,readme,"[{'name': 'README.rst', 'path': 'README.rst', ...",a5ef9890-4c52-5a83-8aa1-c1b266a4f6fb
1,Pyomo/pyomo-gallery,A collection of Pyomo examples,[],315,Jupyter Notebook,https://github.com/Pyomo/pyomo-gallery,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",93cef65a-529e-5666-b09f-751e76cc4621
2,Pyomo/pyomo-tutorials,A modern set of Pyomo tutorials,[],41,Python,https://github.com/Pyomo/pyomo-tutorials,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",3a4e6d0c-cbbe-5ab5-b091-70f35b883ff8
3,norhum/reinforcement-learning-from-scratch,RL for total beginners,[],120,Jupyter Notebook,https://github.com/norhum/reinforcement-learni...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",aef234b1-aa71-5aef-ab2a-b63d9a25b3b4
4,deanmalmgren/textract,extract text from any document. no muss. no fuss.,"[data-mining, natural-language-processing, pyt...",4464,HTML,https://github.com/deanmalmgren/textract,readme,"[{'name': 'README.rst', 'path': 'README.rst', ...",0b546aaa-07f3-567a-8cb7-04e60e9182ca

In [10]:
def process_topics_column(
    df: pd.DataFrame,
    col: str,
    *,
    sep: str = " ",
    slug_sep: str = "-",
    fillna: str = "",
) -> pd.Series:
    """
    Process a DataFrame column whose cells are either a list of strings or a
    plain string, and return a clean, flat string per row.

    Each string in a cell is:
      1. Stripped of leading/trailing whitespace.
      2. Split on `slug_sep` (default "-") so hyphenated slugs like
         "natural-language-processing" become "natural language processing".
      3. Lower-cased.

    The resulting tokens from all strings in a cell are then joined with `sep`
    (default " "), giving a single string per row.  Empty / null cells are
    replaced with `fillna` (default "").

    Args:
        df:       Input DataFrame.
        col:      Name of the column to process.
        sep:      Token join separator for the final string.
        slug_sep: Separator used to split individual slug strings (e.g. "-").
        fillna:   Value to use for rows that are null or produce an empty result.

    Returns:
        A pd.Series of processed strings aligned to `df`'s index.

    Example:
        >>> process_string_column(df, "topics").head()
        0    ai bayesian inference computational science deep learning statistics
        1
        2
        dtype: object
    """

    def _process_cell(cell) -> str:
        if cell is None:
            return fillna

        # Accept both list[str] and a bare str
        items: list[str] = cell if isinstance(cell, list) else [cell]

        tokens: list[str] = []
        for item in items:
            # Split on the slug separator and lower-case each sub-token
            tokens.extend(part.lower() for part in str(item).strip().split(slug_sep) if part)

        return sep.join(tokens) if tokens else fillna

    return df[col].apply(_process_cell)


# --- Demo on the `topics` column ---
df["topics_processed"] = process_topics_column(df, "topics")
df[["repo", "topics", "topics_processed"]].head(10)

,repo,topics,topics_processed
0,pymc-devs/pytensor,"[ai, bayesian-inference, computational-science...",ai bayesian inference computational science de...
1,Pyomo/pyomo-gallery,[],
2,Pyomo/pyomo-tutorials,[],
3,norhum/reinforcement-learning-from-scratch,[],
4,deanmalmgren/textract,"[data-mining, natural-language-processing, pyt...",data mining natural language processing python...
5,ashishps1/awesome-engineering-articles,"[ai, data-engineering, database, distributed-s...",ai data engineering database distributed syste...
6,microsoft/markitdown,"[autogen, autogen-extension, langchain, markdo...",autogen autogen extension langchain markdown m...
7,pyinfra-dev/pyinfra,"[cloud-management, configuration-management, h...",cloud management configuration management high...
8,cognica-io/bayesian-bm25,"[bayesian-bm25, bayesian-inference, bm25, hybr...",bayesian bm25 bayesian inference bm25 hybrid s...
9,chartbeat-labs/textacy,"[natural-language-processing, nlp, python, spacy]",natural language processing nlp python spacy

In [11]:
df['topics_tokenized'] = SearchArray.index(df['topics_processed'], tokenizer=preprocess_text)

2026-03-12 16:40:48,498 - searcharray.indexing - INFO - Indexing begins w/ 4 workers
2026-03-12 16:40:48,499 - searcharray.indexing - INFO - 0 Batch Start tokenization
2026-03-12 16:40:48,499 - searcharray.indexing - INFO - Tokenizing 2049 documents
2026-03-12 16:40:50,149 - searcharray.indexing - INFO - Tokenization -- vstacking
2026-03-12 16:40:50,150 - searcharray.indexing - INFO - Tokenization -- DONE
2026-03-12 16:40:50,151 - searcharray.indexing - INFO - Inverting docs->terms
2026-03-12 16:40:50,153 - searcharray.indexing - INFO - Encoding positions to bit array
2026-03-12 16:40:50,155 - searcharray.indexing - INFO - Batch tokenization complete
2026-03-12 16:40:50,155 - searcharray.indexing - INFO - (main thread) Processing 1 batch results
2026-03-12 16:40:50,157 - searcharray.indexing - INFO - Indexing from tokenization complete

In [12]:
df['description_tokenized'] = SearchArray.index(df['description'], tokenizer=preprocess_text)
df['repo_tokenized'] = SearchArray.index(df['repo'], tokenizer=preprocess_text)

2026-03-12 16:40:50,166 - searcharray.indexing - INFO - Indexing begins w/ 4 workers
2026-03-12 16:40:50,167 - searcharray.indexing - INFO - 0 Batch Start tokenization
2026-03-12 16:40:50,167 - searcharray.indexing - INFO - Tokenizing 2049 documents
2026-03-12 16:40:50,392 - searcharray.indexing - INFO - Tokenization -- vstacking
2026-03-12 16:40:50,392 - searcharray.indexing - INFO - Tokenization -- DONE
2026-03-12 16:40:50,393 - searcharray.indexing - INFO - Inverting docs->terms
2026-03-12 16:40:50,395 - searcharray.indexing - INFO - Encoding positions to bit array
2026-03-12 16:40:50,397 - searcharray.indexing - INFO - Batch tokenization complete
2026-03-12 16:40:50,398 - searcharray.indexing - INFO - (main thread) Processing 1 batch results
2026-03-12 16:40:50,399 - searcharray.indexing - INFO - Indexing from tokenization complete
2026-03-12 16:40:50,401 - searcharray.indexing - INFO - Indexing begins w/ 4 workers
2026-03-12 16:40:50,402 - searcharray.indexing - INFO - 0 Batch Start tokenization
2026-03-12 16:40:50,402 - searcharray.indexing - INFO - Tokenizing 2049 documents
2026-03-12 16:40:50,567 - searcharray.indexing - INFO - Tokenization -- vstacking
2026-03-12 16:40:50,568 - searcharray.indexing - INFO - Tokenization -- DONE
2026-03-12 16:40:50,568 - searcharray.indexing - INFO - Inverting docs->terms
2026-03-12 16:40:50,569 - searcharray.indexing - INFO - Encoding positions to bit array
2026-03-12 16:40:50,571 - searcharray.indexing - INFO - Batch tokenization complete
2026-03-12 16:40:50,571 - searcharray.indexing - INFO - (main thread) Processing 1 batch results
2026-03-12 16:40:50,572 - searcharray.indexing - INFO - Indexing from tokenization complete

In [13]:
df[['repo','description','topics', 'repo_tokenized']].head()

,repo,description,topics,repo_tokenized
0,pymc-devs/pytensor,"PyTensor allows you to define, optimize, and e...","[ai, bayesian-inference, computational-science...","Terms({'devs', 'pytensor', 'pymc'})"
1,Pyomo/pyomo-gallery,A collection of Pyomo examples,[],"Terms({'gallery', 'pyomo'})"
2,Pyomo/pyomo-tutorials,A modern set of Pyomo tutorials,[],"Terms({'tutorial', 'pyomo'})"
3,norhum/reinforcement-learning-from-scratch,RL for total beginners,[],"Terms({'scratch', 'learning', 'norhum', 'reinf..."
4,deanmalmgren/textract,extract text from any document. no muss. no fuss.,"[data-mining, natural-language-processing, pyt...","Terms({'deanmalmgren', 'textract'})"

In [14]:
df['doc_source'].value_counts()

doc_source
readme    2041
Name: count, dtype: int64

In [15]:
df['docs'][0]

[{'name': 'README.rst',
  'path': 'README.rst',
  'size': 4199,
  'content': '.. image:: https://cdn.rawgit.com/pymc-devs/pytensor/main/doc/images/PyTensor_RGB.svg\n    :height: 100px\n    :alt: PyTensor logo\n    :align: center\n\n|Tests Status| |Coverage|\n\n|Project Name| is a Python library that allows one to define, optimize, and\nefficiently evaluate mathematical expressions involving multi-dimensional arrays.\nIt provides the computational backend for `PyMC <https://github.com/pymc-devs/pymc>`__.\n\nFeatures\n========\n\n- A hackable, pure-Python codebase\n- Extensible graph framework suitable for rapid development of custom operators and symbolic optimizations\n- Implements an extensible graph transpilation framework that currently provides\n  compilation via C, `JAX <https://github.com/google/jax>`__, and `Numba <https://github.com/numba/numba>`__\n- Contrary to PyTorch and TensorFlow, PyTensor maintains a static graph which can be modified in-place to\n  allow for advanced optimizations\n\nGetting started\n===============\n\n.. code-block:: python\n\n    import pytensor\n    from pytensor import tensor as pt\n\n    # Declare two symbolic floating-point scalars\n    a = pt.dscalar("a")\n    b = pt.dscalar("b")\n\n    # Create a simple example expression\n    c = a + b\n\n    # Convert the expression into a callable object that takes `(a, b)`\n    # values as input and computes the value of `c`.\n    f_c = pytensor.function([a, b], c)\n\n    assert f_c(1.5, 2.5) == 4.0\n\n    # Compute the gradient of the example expression with respect to `a`\n    dc = pytensor.grad(c, a)\n\n    f_dc = pytensor.function([a, b], dc)\n\n    assert f_dc(1.5, 2.5) == 1.0\n\n    # Compiling functions with `pytensor.function` also optimizes\n    # expression graphs by removing unnecessary operations and\n    # replacing computations with more efficient ones.\n\n    v = pt.vector("v")\n    M = pt.matrix("M")\n\n    d = a/a + (M + a).dot(v)\n\n    pytensor.dprint(d)\n    #  Add [id A]\n    #  ├─ ExpandDims{axis=0} [id B]\n    #  │  └─ True_div [id C]\n    #  │     ├─ a [id D]\n    #  │     └─ a [id D]\n    #  └─ dot [id E]\n    #     ├─ Add [id F]\n    #     │  ├─ M [id G]\n    #     │  └─ ExpandDims{axes=[0, 1]} [id H]\n    #     │     └─ a [id D]\n    #     └─ v [id I]\n\n    f_d = pytensor.function([a, v, M], d)\n\n    # `a/a` -> `1` and the dot product is replaced with a BLAS function\n    # (i.e. CGemv)\n    pytensor.dprint(f_d)\n    # Add [id A] 5\n    #  ├─ [1.] [id B]\n    #  └─ CGemv{inplace} [id C] 4\n    #     ├─ AllocEmpty{dtype=\'float64\'} [id D] 3\n    #     │  └─ Shape_i{0} [id E] 2\n    #     │     └─ M [id F]\n    #     ├─ 1.0 [id G]\n    #     ├─ Add [id H] 1\n    #     │  ├─ M [id F]\n    #     │  └─ ExpandDims{axes=[0, 1]} [id I] 0\n    #     │     └─ a [id J]\n    #     ├─ v [id K]\n    #     └─ 0.0 [id L]\n\nSee `the PyTensor documentation <https://pytensor.readthedocs.io/en/latest/>`__ for in-depth tutorials.\n\n\nInstallation\n============\n\nThe latest release of |Project Name| can be installed from PyPI using ``pip``:\n\n::\n\n    pip install pytensor\n\n\nOr via conda-forge:\n\n::\n\n    conda install -c conda-forge pytensor\n\n\nThe current development branch of |Project Name| can be installed from GitHub, also using ``pip``:\n\n::\n\n    pip install git+https://github.com/pymc-devs/pytensor\n\n\nBackground\n==========\n\nPyTensor is a fork of `Aesara <https://github.com/aesara-devs/aesara>`__, which is a fork of `Theano <https://github.com/Theano/Theano>`__.\n\nContributing\n============\n\nWe welcome bug reports and fixes and improvements to the documentation.\n\nFor more information on contributing, please see the\n`contributing guide <https://pytensor.readthedocs.io/en/latest/dev_start_guide.html>`__.\n\nA good place to start contributing is by looking through the issues\n`here <https://github.com/pymc-devs/pytensor/issues>`__.\n\n\n.. |Project Name| replace:: PyTensor\n.. |Tests Status| image:: https://github.com/pymc-devs/pytensor/workflows/Tests/badge.svg\n  :target: https://github.com/pymc-devs/pytensor/actions?query=workflow%3ATests+branch%3Amain\n.. |Coverage| image:: https://codecov.io/gh/pymc-devs/pytensor/branch/main/graph/badge.svg?token=WVwr8nZYmc\n  :target: https://codecov.io/gh/pymc-devs/pytensor\n'}]

In [16]:
df['docs'][0]

[{'name': 'README.rst',
  'path': 'README.rst',
  'size': 4199,
  'content': '.. image:: https://cdn.rawgit.com/pymc-devs/pytensor/main/doc/images/PyTensor_RGB.svg\n    :height: 100px\n    :alt: PyTensor logo\n    :align: center\n\n|Tests Status| |Coverage|\n\n|Project Name| is a Python library that allows one to define, optimize, and\nefficiently evaluate mathematical expressions involving multi-dimensional arrays.\nIt provides the computational backend for `PyMC <https://github.com/pymc-devs/pymc>`__.\n\nFeatures\n========\n\n- A hackable, pure-Python codebase\n- Extensible graph framework suitable for rapid development of custom operators and symbolic optimizations\n- Implements an extensible graph transpilation framework that currently provides\n  compilation via C, `JAX <https://github.com/google/jax>`__, and `Numba <https://github.com/numba/numba>`__\n- Contrary to PyTorch and TensorFlow, PyTensor maintains a static graph which can be modified in-place to\n  allow for advanced optimizations\n\nGetting started\n===============\n\n.. code-block:: python\n\n    import pytensor\n    from pytensor import tensor as pt\n\n    # Declare two symbolic floating-point scalars\n    a = pt.dscalar("a")\n    b = pt.dscalar("b")\n\n    # Create a simple example expression\n    c = a + b\n\n    # Convert the expression into a callable object that takes `(a, b)`\n    # values as input and computes the value of `c`.\n    f_c = pytensor.function([a, b], c)\n\n    assert f_c(1.5, 2.5) == 4.0\n\n    # Compute the gradient of the example expression with respect to `a`\n    dc = pytensor.grad(c, a)\n\n    f_dc = pytensor.function([a, b], dc)\n\n    assert f_dc(1.5, 2.5) == 1.0\n\n    # Compiling functions with `pytensor.function` also optimizes\n    # expression graphs by removing unnecessary operations and\n    # replacing computations with more efficient ones.\n\n    v = pt.vector("v")\n    M = pt.matrix("M")\n\n    d = a/a + (M + a).dot(v)\n\n    pytensor.dprint(d)\n    #  Add [id A]\n    #  ├─ ExpandDims{axis=0} [id B]\n    #  │  └─ True_div [id C]\n    #  │     ├─ a [id D]\n    #  │     └─ a [id D]\n    #  └─ dot [id E]\n    #     ├─ Add [id F]\n    #     │  ├─ M [id G]\n    #     │  └─ ExpandDims{axes=[0, 1]} [id H]\n    #     │     └─ a [id D]\n    #     └─ v [id I]\n\n    f_d = pytensor.function([a, v, M], d)\n\n    # `a/a` -> `1` and the dot product is replaced with a BLAS function\n    # (i.e. CGemv)\n    pytensor.dprint(f_d)\n    # Add [id A] 5\n    #  ├─ [1.] [id B]\n    #  └─ CGemv{inplace} [id C] 4\n    #     ├─ AllocEmpty{dtype=\'float64\'} [id D] 3\n    #     │  └─ Shape_i{0} [id E] 2\n    #     │     └─ M [id F]\n    #     ├─ 1.0 [id G]\n    #     ├─ Add [id H] 1\n    #     │  ├─ M [id F]\n    #     │  └─ ExpandDims{axes=[0, 1]} [id I] 0\n    #     │     └─ a [id J]\n    #     ├─ v [id K]\n    #     └─ 0.0 [id L]\n\nSee `the PyTensor documentation <https://pytensor.readthedocs.io/en/latest/>`__ for in-depth tutorials.\n\n\nInstallation\n============\n\nThe latest release of |Project Name| can be installed from PyPI using ``pip``:\n\n::\n\n    pip install pytensor\n\n\nOr via conda-forge:\n\n::\n\n    conda install -c conda-forge pytensor\n\n\nThe current development branch of |Project Name| can be installed from GitHub, also using ``pip``:\n\n::\n\n    pip install git+https://github.com/pymc-devs/pytensor\n\n\nBackground\n==========\n\nPyTensor is a fork of `Aesara <https://github.com/aesara-devs/aesara>`__, which is a fork of `Theano <https://github.com/Theano/Theano>`__.\n\nContributing\n============\n\nWe welcome bug reports and fixes and improvements to the documentation.\n\nFor more information on contributing, please see the\n`contributing guide <https://pytensor.readthedocs.io/en/latest/dev_start_guide.html>`__.\n\nA good place to start contributing is by looking through the issues\n`here <https://github.com/pymc-devs/pytensor/issues>`__.\n\n\n.. |Project Name| replace:: PyTensor\n.. |Tests Status| image:: https://github.com/pymc-devs/pytensor/workflows/Tests/badge.svg\n  :target: https://github.com/pymc-devs/pytensor/actions?query=workflow%3ATests+branch%3Amain\n.. |Coverage| image:: https://codecov.io/gh/pymc-devs/pytensor/branch/main/graph/badge.svg?token=WVwr8nZYmc\n  :target: https://codecov.io/gh/pymc-devs/pytensor\n'}]

In [17]:
# Concatenate content from all docs in the list
df['content'] = df['docs'].apply(lambda x: '\n\n'.join(doc['content'] for doc in x) if x else None)

In [18]:
df[['repo','description','description_tokenized','content']].head()

,repo,description,description_tokenized,content
0,pymc-devs/pytensor,"PyTensor allows you to define, optimize, and e...","Terms({'involving', 'expression', 'efficiently...",.. image:: https://cdn.rawgit.com/pymc-devs/py...
1,Pyomo/pyomo-gallery,A collection of Pyomo examples,"Terms({'pyomo', 'collection', 'example'})",[![Project Status: Inactive – The project has ...
2,Pyomo/pyomo-tutorials,A modern set of Pyomo tutorials,"Terms({'modern', 'set', 'tutorial', 'pyomo'})",# Pyomo Tutorials\n\nThis repository hosts a m...
3,norhum/reinforcement-learning-from-scratch,RL for total beginners,"Terms({'beginner', 'total'})",# Reinforcement Learning From Scratch\n\nWelco...
4,deanmalmgren/textract,extract text from any document. no muss. no fuss.,"Terms({'extract', 'fuss', 'text', 'document', ...",.. NOTES FOR CREATING A RELEASE:\n..\n.. * b...

In [19]:
# normalize content
df["content_normalized"] = df["content"].map(
    lambda x: normalize_text_pipeline(x[:MAX_CHARACTERS]) if pd.notna(x) else x
)

In [20]:
df['content_normalized'][10]

"GitButler\n \n \n Git, but better.\n \n GitButler is a modern Git-based version control interface with both a GUI and CLI built from the ground up for AI-powered workflows.\n \n \n Website\n - \n Blog\n - \n Docs\n - \n Downloads\n \n \n \n Our beautiful GUI\n \n Our amazing but CLI\n \n[![TWEET][s1]][l1] [\n![BLUESKY][s8]][l8] [![DISCORD][s2]][l2]\n[![CI][s0]][l0] [![INSTA][s3]][l3] [![YOUTUBE][s5]][l5] [![DEEPWIKI][s7]][l7]\n[s0]: https://github.com/gitbutlerapp/gitbutler/actions/workflows/push.yaml/badge.svg\n[l0]: https://github.com/gitbutlerapp/gitbutler/actions/workflows/push.yaml\n[s1]: https://img.shields.io/badge/Twitter-black?logo=x&logoColor=white\n[l1]: https://twitter.com/intent/follow?screen_name=gitbutler\n[s2]: https://img.shields.io/discord/1060193121130000425?label=Discord&color=5865F2\n[l2]: https://discord.gg/MmFkmaJ42D\n[s3]: https://img.shields.io/badge/Instagram-E4405F?logo=instagram&logoColor=white\n[l3]: https://www.instagram.com/gitbutler/\n[s5]: https://img.shields.io/youtube/channel/subscribers/UCEwkZIHGqsTGYvX8wgD0LoQ\n[l5]: https://www.youtube.com/@gitbutlerapp\n[s7]: https://deepwiki.com/badge.svg\n[l7]: https://deepwiki.com/gitbutlerapp/gitbutler\n[s8]: https://img.shields.io/badge/Bluesky-0285FF?logo=bluesky&logoColor=fff\n[l8]: https://bsky.app/profile/gitbutler.com\nGitButler is a powerful new Git-based version control system, designed from scratch to be simple, powerful and flexible. It is designed for ease of use and modern agentic workflows.\nIt features stacked branches, parallel branches, unlimited undo, easy commit mutations, forge integrations and more.\nWorks instantly in any existing Git repo as a friendlier and more powerful drop-in Git user interface replacement - for you and your agents.\nMain Features\nWhy use GitButler instead of vanilla Git? What a great question.\n- Stacked Branches (gui, cli)\n - Effortlessly create branches stacked on other branches. Amend or edit any commit easily with automatic restacking.\n- Parallel Branches (gui, cli)\n - Organize work on multiple branches simultaneously, rather than constantly switching branches.\n- Easy Commit Management (gui, cli)\n - Uncommit, reword, amend, move, split and squash commits by dragging and dropping or simple CLI commands. Forget about rebase -i, you don't need it anymore.\n- Undo Timeline (gui, cli)\n - Logs all operations and changes and allows you to easily undo or revert any operation.\n- First Class Conflicts (gui, cli)\n - Rebases always succeed. Commits can be marked as conflicted and resolved at any time, in any order.\n- Forge Integration (gui, cli)\n - Authenticate to GitHub or GitLab to easily open and update Pull Requests, list branches, get CI statuses and more. No other tools required.\n- AI Tooling (gui, cli)\n - Use built-in AI handlers to help create commit messages, branch names, PR descriptions and more.\n - Easily install hooks or skills for all modern agent systems to level up their Git management.\nTech\nThe GitButler desktop app is a Tauri-based application. Its UI is written in Svelte using TypeScript and its backend is written in Rust.\nThe but CLI is the same Rust backend engine with a Rust command line UI.\nDocumentation\nYou can find our end user documentation at: \nBugs and Feature Requests\nIf you have a bug or feature request, feel free to open an issue,\nor join our Discord server.\nLicense\nThe TLDR is that GitButler is under a Fair Source software license, meaning that you can use it, view the source, contribute, etc. You just can't build a competitor with it. It also becomes MIT after 2 years. So, MIT with an expiring non-compete clause.\nContributing\nSo you want to help out? Please check out the CONTRIBUTING.md\ndocument.\nIf you want to skip right to getting the code to actually compile, take a look\nat the DEVELOPMENT.md file.\nContributors"

In [21]:
# tokenize content now
df['content_tokenized'] = SearchArray.index(df['content_normalized'], tokenizer=preprocess_text)

2026-03-12 16:40:53,218 - searcharray.indexing - INFO - Indexing begins w/ 4 workers
2026-03-12 16:40:53,218 - searcharray.indexing - INFO - 0 Batch Start tokenization
2026-03-12 16:40:53,219 - searcharray.indexing - INFO - Tokenizing 2049 documents
2026-03-12 16:41:00,334 - searcharray.indexing - INFO - Tokenization -- vstacking
2026-03-12 16:41:00,337 - searcharray.indexing - INFO - Tokenization -- DONE
2026-03-12 16:41:00,344 - searcharray.indexing - INFO - Inverting docs->terms
2026-03-12 16:41:00,547 - searcharray.indexing - INFO - Encoding positions to bit array
2026-03-12 16:41:00,603 - searcharray.indexing - INFO - Batch tokenization complete
2026-03-12 16:41:00,604 - searcharray.indexing - INFO - (main thread) Processing 1 batch results
2026-03-12 16:41:00,623 - searcharray.indexing - INFO - Indexing from tokenization complete

In [22]:
df['score'] = df['content_tokenized'].array.score("awesome")

In [23]:
df.sort_values('score', ascending=False).head(10)

,repo,description,topics,stars,language,url,doc_source,docs,id,topics_processed,topics_tokenized,description_tokenized,repo_tokenized,content,content_normalized,content_tokenized,score
1533,MarcSkovMadsen/awesome-streamlit,The purpose of this project is to share knowle...,"[analytics, apps, awesome-list, data, data-sci...",2243,HTML,https://github.com/MarcSkovMadsen/awesome-stre...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",9369c17d-24eb-5696-a2a6-f992e65cb2bb,analytics apps awesome list data data science ...,"Terms({'apps', 'model', 'python', 'awesome', '...","Terms({'knowledge', 'share', 'awesome', 'proje...","Terms({'awesome', 'streamlit', 'marcskovmadsen'})",# Awesome Streamlit [![Awesome](https://cdn.ra...,Awesome Streamlit ![Awesome](https://github.co...,"Terms({'magic', 'youtu', 'madsen', 'black', 'l...",2.460909
1516,ramitsurana/awesome-kubernetes,A curated list for awesome kubernetes sources ...,"[aws, azure, books, cloud-providers, deploy-ku...",15825,Shell,https://github.com/ramitsurana/awesome-kubernetes,readme,"[{'name': 'README.md', 'path': 'docs/README.md...",f283f1aa-2254-5605-9630-80c59c07024b,aws azure books cloud providers deploy kuberne...,"Terms({'book', 'resource', 'product', 'learnin...","Terms({'curated', 'awesome', 'list', 'ship', '...","Terms({'awesome', 'kubernetes', 'ramitsurana'})",Awesome-Kubernetes\n==========================...,Awesome-Kubernetes\n==========================...,"Terms({'management', 'explained', 'vyas', 'lic...",2.429229
169,LincolnBurrows2017/gauss-awesome-recommender-s...,gauss-awesome-recommender-system-engine,[],122,Python,https://github.com/LincolnBurrows2017/gauss-aw...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",91abb07c-fa69-53c1-8e87-32235ac4a2a4,,Terms(set()),"Terms({'recommender', 'engine', 'system', 'awe...","Terms({'recommender', 'engine', 'system', 'awe...",# Gauss: Awesome Recommender System Engine 🚀\n...,Gauss: Awesome Recommender System Engine 🚀\n!G...,"Terms({'management', 'mostpopular', 'detail', ...",2.401310
1950,jnv/lists,The definitive list of lists (of lists) curate...,"[awesome, awesome-list, curated-lists, lists, ...",11002,None,https://github.com/jnv/lists,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",6a6a505a-45ec-5402-b338-aea20a0047fd,awesome awesome list curated lists lists resou...,"Terms({'awesome', 'resource', 'curated', 'list'})","Terms({'curated', 'github', 'elsewhere', 'defi...","Terms({'jnv', 'list'})","# Lists\n\nList of useful, silly and [awesome]...","Lists\nList of useful, silly and awesome lists...","Terms({'input', 'management', 'belarusian', 'n...",2.398078
61,sickn33/antigravity-awesome-skills,The Ultimate Collection of 900+ Agentic Skills...,"[agentic-skills, ai-agents, antigravity, auton...",18096,Python,https://github.com/sickn33/antigravity-awesome...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",93032f3d-079a-5cb4-bbe7-c25e58755229,agentic skills ai agents antigravity autonomou...,"Terms({'security', 'agent', 'autonomous', 'age...","Terms({'agent', 'agentic', 'antigravity', 'ant...","Terms({'awesome', 'skill', 'sickn', 'antigravi...",# 🌌 Antigravity Awesome Skills: 968+ Agentic S...,🌌 Antigravity Awesome Skills: 968+ Agentic Ski...,"Terms({'net', 'next', 'license', 'djmahe', 'ta...",2.363399
78,brianspiering/awesome-deep-rl,A curated list of awesome Deep Reinforcement L...,[],151,None,https://github.com/brianspiering/awesome-deep-rl,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",bb89d0c8-db30-5379-9b8d-f4b0f5dd3a4f,,Terms(set()),"Terms({'curated', 'awesome', 'list', 'resource...","Terms({'awesome', 'brianspiering', 'deep'})",Awesome Deep Reinforcement Learning [![Awesome...,Awesome Deep Reinforcement Learning ![Awesome]...,"Terms({'agent', 'lunar', 'dopamine', 'lex', 'h...",2.351770
471,zudochkin/awesome-newsletters,A list of amazing Newsletters,"[awesome, awesome-list, email, email-newslette...",4322,None,https://github.com/zudochkin/awesome-newsletters,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",1dbd0153-427b-5c52-9793-faa45ae6877e,awesome awesome list email email newsletter em...,"Terms({'awesome', 'newsletter', 'list', 'email'})","Terms({'amazing', 'newsletter', 'list'})","Terms({'awesome', 'zudochkin', 'newsletter'})","A curated list of newsletters, awesome newslet...","A curated list of newsletters, awesome newslet...","Terms({'management', 'net', 'next', 'license',...",2.345463
1123,mauhai/awesome-jupyterlab,A curated list of awesome JupyterLab extensio...,"[awesome, collections, jupyterlab, jupyterlab-...",2616,None,https://github.com/mauhai/awesome-jupyterlab,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",5bab555b-9ee4-500e-8f8a-738d2247825b,awesome collections jupyterlab jupyterlab exte...,"Terms({'awesome', 'extension', 'jupyterlab', '...","Terms({'curated', 'awesome', 'list', 'resource...","Terms({'awesome', 'jupyterlab', 'mauhai'})",# Awesome JupyterLab[![Awesome](https://cdn.ra...,Awesome JupyterLab![Awesome](https://github.co...,"Terms({'fasta', 'distribution', 'required', 'b...",2.320860
739,EthicalML/awesome-annual-reviews-and-trends,A curated list of awesome year-in-review and a...,[],36,None,https://github.com/EthicalML/awesome-annual-re...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",22095ee8-aa17-5edf-8178-c1848c396ab5,,Terms(set()),"Terms({'curated', 'beyond', 'trend', 'awesome'...","Terms({'trend', 'awesome', 'ethicalml', 'annua...",[![Awesome](https://github.com/EthicalML/aweso...,![Awesome](https://github.com/sindresorhus/awe...,"Terms({'find', 'ordering', 'repository', 'adva...",2.299165
1374,pabloem/awesome-beam,A curated list of awesome resources for Apache...,[],145,None,https://github.com/pabloem/awesome-beam,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",42af1a59-3545-55cf-a2f8-6165e4edf4ec,,Terms(set()),"Terms({'curated', 'beam', 'awesome', 'list', '...","Terms({'awesome', 'beam', 'pabloem'})","[<img src=""https://beam.apache.org/images/logo...",Awesome Beam ![Awesome](https://github.com/sin...,"Terms({'detailing', 'marthi', 'evolution', 'un...",2.261231

In [24]:
awesome_curated_lists = "awesome curated lists"
tokenized_phrase = preprocess_text(awesome_curated_lists)
tokenized_phrase

['awesome', 'curated', 'list']

In [25]:
df['score'] = df['content_tokenized'].array.score(tokenized_phrase)

In [26]:
df.sort_values('score', ascending=False).head(30)

,repo,description,topics,stars,language,url,doc_source,docs,id,topics_processed,topics_tokenized,description_tokenized,repo_tokenized,content,content_normalized,content_tokenized,score
1123,mauhai/awesome-jupyterlab,A curated list of awesome JupyterLab extensio...,"[awesome, collections, jupyterlab, jupyterlab-...",2616,None,https://github.com/mauhai/awesome-jupyterlab,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",5bab555b-9ee4-500e-8f8a-738d2247825b,awesome collections jupyterlab jupyterlab exte...,"Terms({'awesome', 'extension', 'jupyterlab', '...","Terms({'curated', 'awesome', 'list', 'resource...","Terms({'awesome', 'jupyterlab', 'mauhai'})",# Awesome JupyterLab[![Awesome](https://cdn.ra...,Awesome JupyterLab![Awesome](https://github.co...,"Terms({'fasta', 'distribution', 'required', 'b...",3.570782
887,shubhamgrg04/awesome-diagramming,A curated collection of diagramming tools used...,"[awesome-list, diagram, uml]",3225,None,https://github.com/shubhamgrg04/awesome-diagra...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",87f9338c-1ff5-5e64-93c4-24bcfd6ba711,awesome list diagram uml,"Terms({'awesome', 'diagram', 'list', 'uml'})","Terms({'engineering', 'curated', 'leading', 't...","Terms({'awesome', 'shubhamgrg', 'diagramming'})",# Awesome Diagramming [![Awesome](https://cdn....,Awesome Diagramming ![Awesome](https://github....,"Terms({'outdated', 'component', 'hand', 'spark...",3.451823
840,hemansnation/deep-learning-project-ideas,"Curated list of Machine Learning, NLP, Vision,...",[],29,None,https://github.com/hemansnation/deep-learning-...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",1d81f81c-e006-5b24-858c-b705b3148256,,Terms(set()),"Terms({'recommender', 'curated', 'system', 'ma...","Terms({'idea', 'project', 'deep', 'hemansnatio...",<!-- markdownlint-disable MD033 -->\n\n# Aweso...,Awesome Deep Learning Project Ideas\n![Awesome...,"Terms({'million', 'label', 'captioning', 'scho...",2.704698
1373,wuchong/awesome-flink,😎 A curated list of amazingly awesome Flink a...,"[awesome, awesome-flink, awesome-list, flink]",781,None,https://github.com/wuchong/awesome-flink,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",4f86df74-8927-5d0d-8e2c-d050198c5d68,awesome awesome flink awesome list flink,"Terms({'awesome', 'flink', 'list'})","Terms({'curated', 'awesome', 'flink', 'list', ...","Terms({'awesome', 'flink', 'wuchong'})","[<img src=""https://raw.githubusercontent.com/w...",Awesome Flink ![Awesome](https://github.com/si...,"Terms({'unbounded', 'recovery', 'license', 'ta...",2.554654
1019,NirantK/awesome-project-ideas,"Curated list of Machine Learning, NLP, Vision,...","[awesome, awesome-list, classification, datase...",8960,None,https://github.com/NirantK/awesome-project-ideas,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",c64ddcff-35f6-5f3e-b957-23481ef7153c,awesome awesome list classification dataset de...,"Terms({'image', 'awesome', 'multi', 'machine',...","Terms({'recommender', 'curated', 'system', 'ma...","Terms({'awesome', 'idea', 'project', 'nirantk'})",<!-- markdownlint-disable MD033 -->\n\n# Aweso...,Awesome Deep Learning Project Ideas\n![Awesome...,"Terms({'million', 'label', 'captioning', 'blip...",2.509537
1018,costezki/awesome-nlprojects,List of projects related to Natural Language P...,"[awersome-list, machine-learning, natural-lang...",361,None,https://github.com/costezki/awesome-nlprojects,readme,"[{'name': 'readme.md', 'path': 'readme.md', 's...",4060f165-6902-53bc-8e6d-60217fda3ea2,awersome list machine learning natural languag...,"Terms({'language', 'machine', 'list', 'process...","Terms({'language', 'related', 'geek', 'exist',...","Terms({'awesome', 'nlprojects', 'costezki'})",# Awesome NLP Projects\n[![Awesome](https://cd...,Awesome NLP Projects\n![Awesome](https://githu...,"Terms({'input', 'costezki', 'technique', 'appr...",2.161598
713,kengz/awesome-deep-rl,A curated list of awesome Deep Reinforcement L...,"[awesome-list, deep-reinforcement-learning, de...",872,None,https://github.com/kengz/awesome-deep-rl,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",4a61394a-9995-50eb-a77a-dacd5490ed31,awesome list deep reinforcement learning deep ...,"Terms({'awesome', 'list', 'resource', 'deep', ...","Terms({'curated', 'awesome', 'list', 'resource...","Terms({'awesome', 'deep', 'kengz'})",# Awesome Deep RL [![Awesome](https://awesome....,Awesome Deep RL ![Awesome](https://awesome.re)...,"Terms({'nonstationary', 'management', 'trpo', ...",2.092480
1372,youngwookim/awesome-hadoop,A curated list of amazingly awesome Hadoop and...,[],1114,None,https://github.com/youngwookim/awesome-hadoop,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",7dbc56bf-b0c5-5b88-a171-3f676b61191a,,Terms(set()),"Terms({'curated', 'awesome', 'list', 'amazingl...","Terms({'awesome', 'youngwookim', 'hadoop'})",# Awesome Hadoop [![Awesome](https://cdn.rawgi...,Awesome Hadoop ![Awesome](https://github.com/s...,"Terms({'management', 'rhdfs', 'net', 'curator'...",2.027645
1137,wsvincent/awesome-django,A curated list of awesome things related to Dj...,"[awesome, awesome-list, django]",11012,Python,https://github.com/wsvincent/awesome-django,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",e18afc19-c4d7-5fea-b056-72f20f33f4a3,awesome awesome list django,"Terms({'awesome', 'list', 'django'})","Terms({'curated', 'thing', 'awesome', 'list', ...","Terms({'awesome', 'wsvincent', 'django'})",# Awesome Django [![Awesome](https://awesome.r...,Awesome Django ![Awesome](https://github.com/s...,"Terms({'input', 'management', 'linting', 'mptt...",1.708020
285,mjhea0/awesome-fastapi,A curated list of awesome things related to Fa...,"[awesome, awesome-list, fastapi, starlette]",11120,None,https://github.com/mjhea0/awesome-fastapi,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",c4fec4da-7b85-5540-aa31-346a58c8c424,awesome awesome list fastapi starlette,"Terms({'awesome', 'list', 'starlette', 'fastap...","Terms({'curated', 'thing', 'awesome', 'list', ...","Terms({'awesome', 'mjhea', 'fastapi'})",<!--lint disable double-link-->\n\n# Awesome F...,Awesome FastAPI | ![Awesome](https://github.co...,"Terms({'management', 'sars', 'next', 'dispatch...",1.705677
1375,go-training/training,Learning Golang one day,"[golang, training]",1492,HTML,https://github.com/go-training/training,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",5a7eb454-a122-56c5-82a4-8f32af65538d,golang training,"Terms({'golang', 'training'})","Terms({'golang', 'one', 'learning', 'day'})",Terms({'training'}),# Golang Training\n\n[![Run Tests](https://git...,Golang Training\n![Run Tests](https://github.c...,"Terms({'gin', 'sharing', 'testingin', 'fixed',...",0.000000
1366,openai/glide-text2im,GLIDE: a diffusion-based text-conditional imag...,[],3686,Python,https://github.com/openai/glide-text2im,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",5d2d3f03-eacc-5588-9295-f7744313016f,,Terms(set()),"Terms({'based', 'image', 'model', 'diffusion',...","Terms({'openai', 'text', 'glide'})",# GLIDE\n\nThis is the official codebase for r...,GLIDE\nThis is the official codebase for runni...,"Terms({'prompt', 'fill', 'editing', 'directory...",0.000000
1367,mikeckennedy/pythons-gc-and-orms,A simple project to explore the number of GCs ...,[],25,Python,https://github.com/mikeckennedy/pythons-gc-and...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",f6e20b75-4017-5a85-a88b-23060a76c3b9,,Terms(set()),"Terms({'basic', 'explore', 'simple', 'orm', 'g...","Terms({'mikeckennedy', 'orms', 'python'})",# Does Python do extremely too many GCs for OR...,Does Python do extremely too many GCs for ORMs...,"Terms({'txt', 'mongoengine', 'cycle', 'find', ...",0.000000
1368,pathbird/poetry-kernel,Python Jupyter kernel using Poetry for reprodu...,[],248,Python,https://github.com/pathbird/poetry-kernel,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",c90bd9d9-ddaf-58fb-ade0-7897a6db2c0e,,Terms(set()),"Terms({'reproducible', 'poetry', 'python', 'ju...","Terms({'poetry', 'pathbird', 'kernel'})",# Poetry Kernel\n\nUse per-directory Poetry en...,Poetry Kernel\nUse per-directory Poetry enviro...,"Terms({'txt', 'management', 'arbitrary', 'time...",0.000000
1370,GoogleCloudPlatform/ml-design-patterns,Source code accompanying O'Reilly book: Machin...,[],2065,Jupyter Notebook,https://github.com/GoogleCloudPlatform/ml-desi...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",4c2356d8-3f4f-53e7-8042-3d17eb8311a0,,Terms(set()),"Terms({'book', 'machine', 'source', 'design', ...","Terms({'pattern', 'design', 'googlecloudplatfo...",*This is not an official Google product*\n\n# ...,This is not an official Google product\nml-des...,"Terms({'input', 'lens', 'distribution', 'tuned...",0.000000
1369,Zuehlke/ConfZ,ConfZ is a configuration management library fo...,"[config-management, configuration-management, ...",262,Python,https://github.com/Zuehlke/ConfZ,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",bcad790e-3a1c-5952-8621-72896de14305,config management configuration management python,"Terms({'management', 'configuration', 'config'...","Terms({'configuration', 'based', 'management',...","Terms({'zuehlke', 'confz'})",# ConfZ – Pydantic Config Management\n\n[![tes...,ConfZ – Pydantic Config Management\n![test](ht...,"Terms({'management', 'magic', 'behaving', 'dbc...",0.000000
1374,pabloem/awesome-beam,A curated list of awesome resources for Apache...,[],145,None,https://github.com/pabloem/awesome-beam,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",42af1a59-3545-55cf-a2f8-6165e4edf4ec,,Terms(set()),"Terms({'curated', 'beam', 'awesome', 'list', '...","Terms({'awesome', 'beam', 'pabloem'})","[<img src=""https://beam.apache.org/images/logo...",Awesome Beam ![Awesome](https://github.com/sin...,"Terms({'detailing', 'marthi', 'evolution', 'un...",0.000000
1364,JulienPalard/Pipe,A Python library to use infix notation in Python,[],2094,Python,https://github.com/JulienPalard/Pipe,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",e12a8a9c-71fc-5780-adf5-ef3c3ed12625,,Terms(set()),"Terms({'python', 'infix', 'notation', 'library...","Terms({'julienpalard', 'pipe'})",# Pipe — Infix programming toolkit\n\n[![PyPI]...,Pipe — Infix programming toolkit\n![PyPI\n !Mo...,"Terms({'input', 'million', 'eaily', 'apple', '...",0.000000
1371,spotify/big-data-rosetta-code,Code snippets for solving common big data prob...,"[bigdata, scala, scalding, scio, spark]",297,Scala,https://github.com/spotify/big-data-rosetta-code,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",6953a3f7-a9fe-5e6e-9340-05a2c7cf7433,bigdata scala scalding scio spark,"Terms({'scalding', 'bigdata', 'scio', 'spark',...","Terms({'inspired', 'big', 'solving', 'rosetta'...","Terms({'spotify', 'big', 'rosetta', 'data', 'c...",big-data-rosetta-code\n=====================\n...,big-data-rosetta-code\n=====================\n...,"Terms({'status', 'com', 'scalding', 'rosetta',...",0.000000
1365,cdgriffith/Box,Python dictionaries with advanced dot notation...,"[addict, box, bunch, dictionaries, helper, obj...",2821,Python,https://github.com/cdgriffith/Box,readme,"[{'name': 'README.rst', 'path': 'README.rst', ...",5589a694-4b46-5b38-9a36-7561b096793f,addict box bunch dictionaries helper object py...,"Terms({'helper', 'pypi', 'python', 'object', '...","Terms({'dot', 'python', 'access', 'dictionary'...","Terms({'cdgriffith', 'box'})",|BuildStatus| |License|\n\n|BoxImage|\n\n.. co...,|BuildStatus| |License|\n|BoxImage|\n.. code::...,"Terms({'img', 'txt', 'committee', 'added', 'ke...",0.000000
0,pymc-devs/pytensor,"PyTensor allows you to define, optimize, and e...","[ai, bayesian-inference, computational-science...",594,Python,https://github.com/pymc-devs/pytensor,readme,"[{'name': 'README.rst', 'path': 'README.rst', ...",a5ef9890-4c52-5a83-8aa1-c1b266a4f6fb,ai bayesian inference computational science de...,"Terms({'computational', 'bayesian', 'science',...","Terms({'involving', 'expression', 'efficiently...","Terms({'devs', 'pytensor', 'pymc'})",.. image:: https://cdn.rawgit.com/pymc-devs/py...,.. image:: https://cdn.rawgit.com/pymc-devs/py...,"Terms({'input', 'ax', 'maintains', 'currently'...",0.000000
1363,jalammar/ecco,"Explain, analyze, and visualize NLP language m...","[explorables, language-models, natural-languag...",2084,Jupyter Notebook,https://github.com/jalammar/ecco,readme,"[{'name': 'readme.md', 'path': 'readme.md', 's...",de91f7c7-b620-5de5-923f-66a2f4b6effe,explorables language models natural language p...,"Terms({'language', 'model', 'processing', 'nlp...","Terms({'based', 'language', 'gpt', 'ecco', 'ro...","Terms({'jalammar', 'ecco'})","\n<img src=""https://ar.pegg.io/img/ecco-logo-w...",![GitHub - License][#github-license]\n![PyPI -...,"Terms({'input', 'lens', 'evolution', 'built', ...",0.000000
1362,oegedijk/explainerdashboard,Quickly build Explainable AI dashboards that s...,"[dash, dashboard, data-scientists, explainer, ...",2477,Python,https://github.com/oegedijk/explainerdashboard,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",922142d5-272d-57fb-8b74-ac733969df9d,dash dashboard data scientists explainer inner...,"Terms({'plot', 'scientist', 'model', 'dashboar...","Terms({'called', 'build', 'model', 'dashboard'...","Terms({'explainerdashboard', 'oegedijk'})",![GitHub Workflow Status (with event)](https:/...,!GitHub Workflow Status (with event)\n!https:/...,"Terms({'hidewinsor', 'input', 'whatifcomposite...",0.000000
1376,dennyzhang/cheatsheet-golang-A4,:book: Advanced Golang Syntax In A4,"[awesome, cheatsheet, denny-cheatsheets, golang]",67,Go,https://github.com/dennyzhang/cheatsheet-golan...,readme,"[{'name': 'README.org', 'path': 'README.org', ...",6511ca19-ae9c-5f68-8968-52edc028b32c,awesome cheatsheet denny cheatsheets golang,"Terms({'awesome', 'cheatsheet', 'denny', 'gola...","Terms({'book', 'golang', 'syntax', 'advanced'})","Terms({'dennyzhang', 'golang', 'cheatsheet'})",* Golang CheatSheet ...,Golang CheatSheet :Languages:\n:PROPERTIES:\n:...,"Terms({'arbitrary', 'management', 'label', 'ac...",0.000000
1360,benedekrozemberczki/shapley,"The official implementation of ""The Shapley Va...","[classifier, deep-learning, ensemble, ensemble...",224,Python,https://github.com/benedekrozemberczki/shapley,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",eb028460-d571-57f7-a0ff-24a0c77531ba,classifier deep learning ensemble ensemble lea...,"Terms({'forest', 'ensemble', 'owen', 'machine'...","Terms({'implementation', 'game', 'shapley', 'c...","Terms({'benedekrozemberczki', 'shapley'})",[pypi-image]: https://badge.fury.io/py/shapley...,[pypi-image]: https://badge.fury.io/py/shapley...,"Terms({'img', 'management', 'directory', 'pool...",0.000000
1359,microsoft/maro,Multi-Agent Resource Optimization (MARO) platf...,"[agent, citi-bike, docker, finance, inventory-...",910,Python,https://github.com/microsoft/maro,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",408106cd-4b2a-580b-9869-13c61dd5d53a,agent citi bike docker finance inventory manag...,"Terms({'management', 'agent', 'resource', 'mul...","Terms({'optimization', 'real', 'agent', 'servi...","Terms({'microsoft', 'maro'})",[![License](https://img.shields.io/pypi/l/pyma...,![License](https://github.com/microsoft/maro/b...,"Terms({'management', 'actor', 'license', 'dist...",0.000000
1358,niedakh/pqdm,Comfortable parallel TQDM using concurrent.fut...,"[concurrent-futures, parallel-computing, progr...",298,Python,https://github.com/niedakh/pqdm,readme,"[{'name': 'README.rst', 'path': 'README.rst', ...",4dd14803-1b09-55d8-b871-e01efe6adf50,concurrent futures parallel computing progress...,"Terms({'python', 'future', 'concurrent', 'para...","Terms({'future', 'concurrent', 'parallel', 'us...","Terms({'niedakh', 'pqdm'})",=============\nParallel TQDM\n=============\n\...,=============\nParallel TQDM\n=============\n....,"Terms({'img', 'pypackage', 'license', 'python'...",0.000000
1357,alirezamika/autoscraper,"A Smart, Automatic, Fast and Lightweight Web S...","[ai, artificial-intelligence, automation, craw...",7108,Python,https://github.com/alirezamika/autoscraper,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",876fa999-2b9d-5a02-8546-2f3e9d75e1ef,ai artificial intelligence automation crawler ...,"Terms({'python', 'scraping', 'web', 'crawler',...","Terms({'web', 'python', 'fast', 'lightweight',...","Terms({'autoscraper', 'alirezamika'})","# AutoScraper: A Smart, Automatic, Fast and Li...","AutoScraper: A Smart, Automatic, Fast and Ligh...","Terms({'img', 'built', 'smart', 'cap', 'extern...",0.000000
1356,ourownstory/neural_prophet,NeuralProphet: A simple forecasting package,"[artificial-intelligence, autoregression, deep...",4248,Python,https://github.com/ourownstory/neural_prophet,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",005f096f-5f55-5e05-b99e-92d5ae394f67,artificial intelligence autoregression deep le...,"Terms({'trend', 'time', 'seasonality', 'foreca...","Terms({'forecasting', 'package', 'neuralprophe...","Terms({'prophet', 'neural', 'ourownstory'})",[![GitHub release (latest SemVer)](https://img...,![GitHub release (latest SemVer)](https://gith...,"Terms({'net', 'reliable', 'black', 'license', ...",0.000000
1355,relastle/glacier,:snowflake: Building Python CLI using docstri...,"[asyncio, cli, command-line-tool, docstring, l...",98,Python,https://github.com/relastle/glacier,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",b5e7fe83-5f75-5304-9ca0-af0fa5326ab0,asyncio cli command line tool docstring librar...,"Terms({'productivity', 'python', 'cli', 'async...","Terms({'python', 'typehints', 'cli', 'building...","Terms({'glacier', 'relastle'})",![image](https://user-images.githubusercontent...,!image\nglacier\nglacier is a python CLI build...,"Terms({'stage', 'alone', 'whose', 'note', 'lic...",0.000000

In [27]:
def multi_match_search(query: str, df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    # Tokenize the query using each column's own tokenizer
    tokenized_queries = {
        col: df[col].array.tokenizer(query)
        for col in columns
    }

    # Score each column for each query term → shape (num_terms x num_docs) per column
    field_scores = {
        col: np.asarray([df[col].array.score(term) for term in tokenized_queries[col]])
        for col in columns
    }

    # Determine the number of terms from the first column
    num_terms = max(len(scores) for scores in field_scores.values())

    # For each term, take the element-wise max score across all columns (dismax)
    best_term_scores_per_doc = []
    for term_idx in range(num_terms):
        term_scores_across_fields = [
            field_scores[col][term_idx]
            for col in columns
            if term_idx < len(field_scores[col])
        ]
        best_score = np.max(term_scores_across_fields, axis=0)
        best_term_scores_per_doc.append(best_score)

    # Sum the best-field scores across all terms for the final document score
    result = df.copy()
    result['score'] = np.sum(best_term_scores_per_doc, axis=0)
    return result.sort_values('score', ascending=False)

In [28]:
results = multi_match_search(
    query="awesome curated lists",
    df=df,
    columns=["repo_tokenized", "topics_tokenized", "description_tokenized", "content_tokenized"],
)

In [32]:
# Show all rows
cols_to_export = ['id','repo', 'description', 'topics', 'language','url', 'doc_source', 'score']
pd.set_option('display.max_rows', 200)
results[cols_to_export].head(20)

,id,repo,description,topics,language,url,doc_source,score
1950,6a6a505a-45ec-5402-b338-aea20a0047fd,jnv/lists,The definitive list of lists (of lists) curate...,"[awesome, awesome-list, curated-lists, lists, ...",None,https://github.com/jnv/lists,readme,8.930840
471,1dbd0153-427b-5c52-9793-faa45ae6877e,zudochkin/awesome-newsletters,A list of amazing Newsletters,"[awesome, awesome-list, email, email-newslette...",None,https://github.com/zudochkin/awesome-newsletters,readme,7.235460
675,62762741-11e6-5e42-9d12-8e8101f7469d,ddotta/awesome-polars,"A curated list of Polars talks, tools, example...","[awesome, awesome-list, collection, curated-li...",None,https://github.com/ddotta/awesome-polars,readme,7.233369
1524,9647593c-9b19-5b13-b2ef-744125cd6f1e,aporia-ai/mlops.toys,"🎲 A curated list of MLOps projects, tools and ...","[awesome, awesome-list, data-science, list, ma...",Vue,https://github.com/aporia-ai/mlops.toys,readme,6.951973
88,7636125b-0534-500b-b0b9-22717eeefb11,awesomelistsio/awesome-reinforcement-learning,"A curated list of awesome frameworks, librarie...","[awesome, awesome-list, awesome-lists, reinfor...",Python,https://github.com/awesomelistsio/awesome-rein...,readme,6.851551
1137,e18afc19-c4d7-5fea-b056-72f20f33f4a3,wsvincent/awesome-django,A curated list of awesome things related to Dj...,"[awesome, awesome-list, django]",Python,https://github.com/wsvincent/awesome-django,readme,6.793023
1881,a4ebee38-74c6-5779-b331-0c15a5d58b9b,pditommaso/awesome-pipeline,A curated list of awesome pipeline toolkits in...,"[awesome-list, workflow]",None,https://github.com/pditommaso/awesome-pipeline,readme,6.739195
285,c4fec4da-7b85-5540-aa31-346a58c8c424,mjhea0/awesome-fastapi,A curated list of awesome things related to Fa...,"[awesome, awesome-list, fastapi, starlette]",None,https://github.com/mjhea0/awesome-fastapi,readme,6.574901
887,87f9338c-1ff5-5e64-93c4-24bcfd6ba711,shubhamgrg04/awesome-diagramming,A curated collection of diagramming tools used...,"[awesome-list, diagram, uml]",None,https://github.com/shubhamgrg04/awesome-diagra...,readme,6.521213
1373,4f86df74-8927-5d0d-8e2c-d050198c5d68,wuchong/awesome-flink,😎 A curated list of amazingly awesome Flink a...,"[awesome, awesome-flink, awesome-list, flink]",None,https://github.com/wuchong/awesome-flink,readme,6.479270
739,22095ee8-aa17-5edf-8178-c1848c396ab5,EthicalML/awesome-annual-reviews-and-trends,A curated list of awesome year-in-review and a...,[],None,https://github.com/EthicalML/awesome-annual-re...,readme,6.203630
283,bf440b15-fb4d-5e6e-aac6-46124946c73c,fffaraz/awesome-cpp,A curated list of awesome C++ (or C) framework...,"[awesome, awesome-list, c, c-plus-plus, cpp, c...",None,https://github.com/fffaraz/awesome-cpp,readme,6.158941
1516,f283f1aa-2254-5605-9630-80c59c07024b,ramitsurana/awesome-kubernetes,A curated list for awesome kubernetes sources ...,"[aws, azure, books, cloud-providers, deploy-ku...",Shell,https://github.com/ramitsurana/awesome-kubernetes,readme,6.136012
1961,102480a9-60d3-56ee-b142-3573a3b9c9a8,visenger/awesome-mlops,A curated list of references for MLOps,"[ai, data-science, devops, engineering, federa...",None,https://github.com/visenger/awesome-mlops,readme,6.003039
717,b5f0b508-114b-5d97-8c31-36b3b190a4da,DovAmir/awesome-design-patterns,A curated list of software and architecture re...,"[architecture, awesome, awesome-list, cloud-co...",None,https://github.com/DovAmir/awesome-design-patt...,readme,5.968225
1123,5bab555b-9ee4-500e-8f8a-738d2247825b,mauhai/awesome-jupyterlab,A curated list of awesome JupyterLab extensio...,"[awesome, collections, jupyterlab, jupyterlab-...",None,https://github.com/mauhai/awesome-jupyterlab,readme,5.893960
1374,42af1a59-3545-55cf-a2f8-6165e4edf4ec,pabloem/awesome-beam,A curated list of awesome resources for Apache...,[],None,https://github.com/pabloem/awesome-beam,readme,5.834331
1874,551634f3-7fc6-5b31-a676-b693e59d648c,theanalyst/awesome-distributed-systems,A curated list to learn about distributed systems,"[architecture, consensus, distributed-systems,...",None,https://github.com/theanalyst/awesome-distribu...,readme,5.804758
78,bb89d0c8-db30-5379-9b8d-f4b0f5dd3a4f,brianspiering/awesome-deep-rl,A curated list of awesome Deep Reinforcement L...,[],None,https://github.com/brianspiering/awesome-deep-rl,readme,5.733269
1937,8ca301dc-cd7d-5502-a5a8-4f9a88db7cad,Palashio/awesome-libra,A curated list of all things related to libra.,[],None,https://github.com/Palashio/awesome-libra,readme,5.604686

In [30]:
## TODO: tokenize more fields and search with multi-match-search function
results.shape

(2049, 17)

In [35]:
# export to CSV and spreadsheet
results[cols_to_export].sort_values('score', ascending=False).to_csv("../data/processed/github_scores.csv", index=False)

In [38]:
 # Read only specific columns
results_ann = pd.read_csv("../data/processed/github_scores_annotated.csv")
results_ann.head()

,repo,topics,language,id,description,url,doc_source,score,is_a_curated_list,is_not_a_library
0,jnv/lists,"['awesome', 'awesome-list', 'curated-lists', '...",NaN,6a6a505a-45ec-5402-b338-aea20a0047fd,The definitive list of lists (of lists) curate...,https://github.com/jnv/lists,readme,8.930841,1.0,1.0
1,zudochkin/awesome-newsletters,"['awesome', 'awesome-list', 'email', 'email-ne...",NaN,1dbd0153-427b-5c52-9793-faa45ae6877e,A list of amazing Newsletters,https://github.com/zudochkin/awesome-newsletters,readme,7.235460,1.0,1.0
2,ddotta/awesome-polars,"['awesome', 'awesome-list', 'collection', 'cur...",NaN,62762741-11e6-5e42-9d12-8e8101f7469d,"A curated list of Polars talks, tools, example...",https://github.com/ddotta/awesome-polars,readme,7.233369,1.0,1.0
3,aporia-ai/mlops.toys,"['awesome', 'awesome-list', 'data-science', 'l...",Vue,9647593c-9b19-5b13-b2ef-744125cd6f1e,"🎲 A curated list of MLOps projects, tools and ...",https://github.com/aporia-ai/mlops.toys,readme,6.951973,1.0,1.0
4,awesomelistsio/awesome-reinforcement-learning,"['awesome', 'awesome-list', 'awesome-lists', '...",Python,7636125b-0534-500b-b0b9-22717eeefb11,"A curated list of awesome frameworks, librarie...",https://github.com/awesomelistsio/awesome-rein...,readme,6.851551,1.0,1.0

In [39]:
def multi_match_search(
    query: str,
    df: pd.DataFrame,
    columns: list[str],
    boosts: dict[str, float] | None = None
) -> pd.DataFrame:
    # Default all boosts to 1.0 if not provided
    if boosts is None:
        boosts = {}
    boost_values = {col: boosts.get(col, 1.0) for col in columns}

    # Tokenize the query using each column's own tokenizer
    tokenized_queries = {
        col: df[col].array.tokenizer(query)
        for col in columns
    }

    # Score each column for each query term → shape (num_terms x num_docs) per column
    # Apply the boost multiplier to each field's scores here
    field_scores = {
        col: np.asarray([df[col].array.score(term) for term in tokenized_queries[col]]) * boost_values[col]
        for col in columns
    }

    # Determine the number of terms from the longest tokenized query
    num_terms = max(len(scores) for scores in field_scores.values())

    # For each term, take the element-wise max score across all columns (dismax)
    best_term_scores_per_doc = []
    for term_idx in range(num_terms):
        term_scores_across_fields = [
            field_scores[col][term_idx]
            for col in columns
            if term_idx < len(field_scores[col])
        ]
        best_score = np.max(term_scores_across_fields, axis=0)
        best_term_scores_per_doc.append(best_score)

    # Sum the best-field scores across all terms for the final document score
    result = df.copy()
    result['score'] = np.sum(best_term_scores_per_doc, axis=0)
    return result.sort_values('score', ascending=False)

In [41]:
results2 = multi_match_search(
    query="awesome curated lists",
    df=df,
    columns=["repo_tokenized", "topics_tokenized", "description_tokenized", "content_tokenized"],
    boosts={"repo_tokenized": 3.0, "topics_tokenized": 2.0, "description_tokenized": 1.5}
)

In [47]:
# Keep only what you need before joining to avoid column name collisions
comparison = results_ann[['id', 'repo', 'topics', 'description', 'score', 'is_a_curated_list', 'is_not_a_library']].merge(
    results2[['id', 'score']],
    on='id',
    suffixes=('_v1', '_v2')
)

In [54]:
comparison.head(20)

,id,repo,topics,description,score_v1,is_a_curated_list,is_not_a_library,score_v2
0,6a6a505a-45ec-5402-b338-aea20a0047fd,jnv/lists,"['awesome', 'awesome-list', 'curated-lists', '...",The definitive list of lists (of lists) curate...,8.930841,1.0,1.0,20.959242
1,1dbd0153-427b-5c52-9793-faa45ae6877e,zudochkin/awesome-newsletters,"['awesome', 'awesome-list', 'email', 'email-ne...",A list of amazing Newsletters,7.235460,1.0,1.0,11.148891
2,62762741-11e6-5e42-9d12-8e8101f7469d,ddotta/awesome-polars,"['awesome', 'awesome-list', 'collection', 'cur...","A curated list of Polars talks, tools, example...",7.233369,1.0,1.0,14.590599
3,9647593c-9b19-5b13-b2ef-744125cd6f1e,aporia-ai/mlops.toys,"['awesome', 'awesome-list', 'data-science', 'l...","🎲 A curated list of MLOps projects, tools and ...",6.951973,1.0,1.0,12.115523
4,7636125b-0534-500b-b0b9-22717eeefb11,awesomelistsio/awesome-reinforcement-learning,"['awesome', 'awesome-list', 'awesome-lists', '...","A curated list of awesome frameworks, librarie...",6.851551,1.0,1.0,12.145926
5,e18afc19-c4d7-5fea-b056-72f20f33f4a3,wsvincent/awesome-django,"['awesome', 'awesome-list', 'django']",A curated list of awesome things related to Dj...,6.793023,1.0,1.0,12.669821
6,a4ebee38-74c6-5779-b331-0c15a5d58b9b,pditommaso/awesome-pipeline,"['awesome-list', 'workflow']",A curated list of awesome pipeline toolkits in...,6.739195,1.0,1.0,11.817943
7,c4fec4da-7b85-5540-aa31-346a58c8c424,mjhea0/awesome-fastapi,"['awesome', 'awesome-list', 'fastapi', 'starle...",A curated list of awesome things related to Fa...,6.574901,1.0,1.0,12.233577
8,87f9338c-1ff5-5e64-93c4-24bcfd6ba711,shubhamgrg04/awesome-diagramming,"['awesome-list', 'diagram', 'uml']",A curated collection of diagramming tools used...,6.521213,1.0,1.0,11.288593
9,4f86df74-8927-5d0d-8e2c-d050198c5d68,wuchong/awesome-flink,"['awesome', 'awesome-flink', 'awesome-list', '...",😎 A curated list of amazingly awesome Flink a...,6.479270,1.0,1.0,12.135574
10,22095ee8-aa17-5edf-8178-c1848c396ab5,EthicalML/awesome-annual-reviews-and-trends,[],A curated list of awesome year-in-review and a...,6.203630,1.0,1.0,8.102716
11,bf440b15-fb4d-5e6e-aac6-46124946c73c,fffaraz/awesome-cpp,"['awesome', 'awesome-list', 'c', 'c-plus-plus'...",A curated list of awesome C++ (or C) framework...,6.158941,1.0,1.0,11.368316
12,f283f1aa-2254-5605-9630-80c59c07024b,ramitsurana/awesome-kubernetes,"['aws', 'azure', 'books', 'cloud-providers', '...",A curated list for awesome kubernetes sources ...,6.136012,1.0,1.0,9.535966
13,102480a9-60d3-56ee-b142-3573a3b9c9a8,visenger/awesome-mlops,"['ai', 'data-science', 'devops', 'engineering'...",A curated list of references for MLOps,6.003039,1.0,1.0,10.508368
14,b5f0b508-114b-5d97-8c31-36b3b190a4da,DovAmir/awesome-design-patterns,"['architecture', 'awesome', 'awesome-list', 'c...",A curated list of software and architecture re...,5.968225,1.0,1.0,10.940893
15,5bab555b-9ee4-500e-8f8a-738d2247825b,mauhai/awesome-jupyterlab,"['awesome', 'collections', 'jupyterlab', 'jupy...",A curated list of awesome JupyterLab extension...,5.893960,1.0,1.0,9.823368
16,42af1a59-3545-55cf-a2f8-6165e4edf4ec,pabloem/awesome-beam,[],A curated list of awesome resources for Apache...,5.834331,1.0,1.0,9.823368
17,551634f3-7fc6-5b31-a676-b693e59d648c,theanalyst/awesome-distributed-systems,"['architecture', 'consensus', 'distributed-sys...",A curated list to learn about distributed systems,5.804758,1.0,1.0,9.576292
18,bb89d0c8-db30-5379-9b8d-f4b0f5dd3a4f,brianspiering/awesome-deep-rl,[],A curated list of awesome Deep Reinforcement L...,5.733269,1.0,1.0,9.535966
19,8ca301dc-cd7d-5502-a5a8-4f9a88db7cad,Palashio/awesome-libra,[],A curated list of all things related to libra.,5.604686,1.0,1.0,10.145296

In [49]:
comparison.query('score_v1 < 0 and score_v2 > 0')

Empty DataFrame
Columns: [id, repo, topics, description, score_v1, is_a_curated_list, is_not_a_library, score_v2]
Index: []

In [56]:
comparison.query('is_a_curated_list == 1').sort_values('score_v2', ascending=True)

,id,repo,topics,description,score_v1,is_a_curated_list,is_not_a_library,score_v2
203,688f34a1-1e63-5699-bfd4-fc39eda17a28,eugeneyan/applied-ml,"['applied-data-science', 'applied-machine-lear...",📚 Papers & tech blogs by companies sharing the...,1.019706,1.0,1.0,1.019706
192,78a29dca-4c58-56a3-b009-ec50a982cb0f,Nyandwi/machine_learning_complete,"['computer-vision', 'data-analysis', 'data-sci...",A comprehensive machine learning repository co...,1.140272,1.0,0.0,1.140272
187,8608f534-a0d4-598b-9eba-fd1c909d0b24,Rishabh-creator601/Books,"['computer-vision', 'cpp', 'deep-learning', 'd...",Books / PDFS / EPUBS for different fields of p...,1.201308,1.0,1.0,1.201308
184,1016bca9-95ad-5e1b-b8c8-a5163f7da5e9,dair-ai/ML-Papers-Explained,[],Explanation to key concepts in ML,1.225630,1.0,1.0,1.225630
152,7144519b-186a-5bd9-bafb-936670346a95,chihming/competitive-recsys,"['collaborative-filtering', 'recommendation-al...",A collection of resources for Recommender Syst...,1.603412,1.0,1.0,1.603412
144,670b5771-2b9d-5720-b1e7-2b59a6705fda,NirDiamant/RAG_Techniques,"['ai', 'langchain', 'llama-index', 'llm', 'llm...",This repository showcases various advanced tec...,1.714251,1.0,1.0,1.714251
136,3f995872-441f-5fde-9635-c13fcc7808c5,CodeCutTech/Data-science,"['articles', 'artificial-intelligence', 'data-...",Collection of useful data science topics along...,1.759038,1.0,1.0,1.759038
134,caf93575-2b5f-5b9e-91f4-e0c348a9431d,ashishps1/learn-ai-engineering,"['agentic-ai', 'agents', 'ai', 'deep-learning'...",Learn AI and LLMs from scratch using free reso...,1.796410,1.0,1.0,1.796410
109,6f9c8926-52e0-51ee-8f70-2088c093cb6b,AkashSingh3031/The-Complete-FAANG-Preparation,"['algorithms', 'aptitude', 'collaborate', 'com...","Dive into this repository, a comprehensive res...",2.107226,1.0,1.0,2.107226
107,61250239-b16b-53bc-af8f-7de5a9e2e3b3,realpython/discover-flask,[],Full Stack Web Development with Flask.,2.134127,1.0,1.0,2.134127
166,b42a260b-1230-5e1c-9882-9af80604d64c,deep-learning-drizzle/deep-learning-drizzle.gi...,"['computer-vision', 'deep-learning', 'deep-neu...",webpage for maintaining the list of openly ava...,1.487752,1.0,1.0,2.231628
159,098019fa-0920-5e20-a1ec-6c5407c76fdd,dbohdan/structured-text-tools,"['awk', 'cli', 'configuration-file', 'conversi...",A list of command-line tools for manipulating ...,1.563470,1.0,1.0,2.345205
153,601a986f-14da-5723-9df0-c827a8fdb834,SkalskiP/courses,"['computer-vision', 'deep-learning', 'deep-neu...",This repository is a curated collection of lin...,1.602069,1.0,1.0,2.349327
91,c11cf7dc-6e51-56ca-98d3-916f8f28f494,thubZ09/vision-language-model-research,"['computer-vision', 'deep-learning', 'machine-...",Hub for researchers exploring VLMs and Multimo...,2.524721,1.0,1.0,2.524721
198,95b561fd-325e-5cdf-b5a5-0aa81166fde4,guyulongcs/Awesome-Deep-Learning-Papers-for-Se...,"['advertising', 'ctr', 'cvr', 'deep-learning',...",Awesome Deep Learning papers for industrial Se...,1.071771,1.0,1.0,2.579466
139,577005be-d457-5cec-8e92-d9f54bba6dda,FavioVazquez/ds-cheatsheets,"['cheatsheet', 'datascience', 'jupyter', 'prog...",List of Data Science Cheatsheets to rule the w...,1.740648,1.0,1.0,2.610971
138,cf1ce42f-d5fa-50f1-b23d-7be1ed94f956,Developer-Y/cs-video-courses,"['algorithms', 'bioinformatics', 'computationa...",List of Computer Science courses with video le...,1.740648,1.0,1.0,2.610971
87,19a49185-4af6-55c9-b9db-5545fab31c47,alexeygrigorev/data-science-interviews,"['data-science', 'data-science-interviews', 'i...",Data science interview questions and answers,2.713821,1.0,1.0,2.713821
86,98da642a-4a2e-566c-9871-792ab014f9f7,openai/spinningup,[],An educational resource to help anyone learn d...,2.767177,1.0,1.0,2.767177
80,94bb60a3-7135-52e4-af3c-e448f59ad48a,pysemtec/semantic-python-overview,"['collection', 'community-driven', 'datalog', ...",(subjective) overview of projects which are re...,2.839143,1.0,1.0,2.839143
76,3efbbb6e-2604-5ea0-add9-673cf7c23d19,ashishpatel26/500-AI-Machine-learning-Deep-lea...,"['artificial-intelligence', 'artificial-intell...",500 AI Machine learning Deep learning Computer...,2.912994,1.0,1.0,2.912994
151,5e5cc497-50c5-522b-9662-8e2154a37a17,rougier/ML-Recipes,"['algorithm', 'awesome', 'machine-learning', '...",A collection of stand-alone Python machine lea...,1.607495,1.0,1.0,3.214989
71,39135dff-5858-5b4a-bc85-5d732ecf059e,bmorelli25/Become-A-Full-Stack-Web-Developer,[],Free resources for learning Full Stack Web Dev...,3.222230,1.0,1.0,3.222230
116,cd18a81d-97b5-5176-ad5c-fbdcc0235ae7,zzsza/Awesome-Mobility-Machine-Learning-Contents,[],Machine Learning / Deep Learning Contents in M...,2.028187,1.0,1.0,3.452000
174,99dc20b9-4672-5286-a491-178fa3ae8764,ashishps1/awesome-low-level-design,"['awesome', 'design-patterns', 'interview', 'i...",Learn Low Level Design (LLD) and prepare for i...,1.359674,1.0,1.0,3.454376
177,597e6247-805f-51fd-a4cd-f1b5b8a5f592,ashishps1/awesome-system-design-resources,"['awesome', 'backend', 'computer-science', 'di...",Learn System Design concepts and prepare for i...,1.310457,1.0,1.0,3.454376
190,c59e4658-780b-5d49-a43c-3a93724cb06f,AI-Maker-Space/Awesome-AIM-Index,[],An index of all of our weekly concepts + code ...,1.151458,1.0,1.0,3.454376
135,c4a114b7-216f-5310-95c4-d83a94d3c096,Plankson/awesome-explainable-reinforcement-lea...,"['explainable-reinforcement-learning', 'reinfo...",A Survey on Explainable Reinforcement Learning...,1.775933,1.0,1.0,3.766495
81,91abb07c-fa69-53c1-8e87-32235ac4a2a4,LincolnBurrows2017/gauss-awesome-recommender-s...,[],gauss-awesome-recommender-system-engine,2.823666,1.0,1.0,3.768163
84,4ca2aae5-4be8-5cf2-b68f-8344c681b41c,louisfb01/best_AI_papers_2021,"['2021', 'ai', 'artificial-intelligence', 'art...",A curated list of the latest breakthroughs in...,2.805305,1.0,1.0,3.837554
103,7b52fab1-e7fa-5b1a-ae7d-31fc62e25a62,papers-we-love/papers-we-love,"['awesome', 'computer-science', 'meetup', 'pap...",Papers from the computer science community to ...,2.212077,1.0,1.0,3.891761
150,7aed6213-3b9f-5c56-a36b-bb5346e9d982,rguo12/awesome-causality-data,[],A data index for learning causality.,1.617253,1.0,1.0,3.894714
170,f379036a-6b94-566f-ba08-a66a782e920d,rguo12/awesome-causality-algorithms,"['awesome', 'baselines', 'causal-inference', '...",An index of algorithms for learning causality ...,1.409074,1.0,1.0,3.894714
105,0d7e29c6-c8c5-5cf6-b579-0447db064f04,Bogdanp/awesome-advent-of-code,"['advent-of-code', 'advent-of-code-2018', 'adv...",A collection of awesome resources related to t...,2.146670,1.0,1.0,4.151410
58,0044d05a-82a2-5871-afac-93f59c2a2956,yangshun/tech-interview-handbook,"['algorithm', 'algorithm-interview', 'algorith...",Curated coding interview preparation materials...,3.786222,1.0,1.0,4.194734
101,c1669d9b-ca69-506a-b759-17a262af4ad8,EthicalML/awesome-artificial-intelligence-regu...,"['ai', 'ai-ethics', 'ai-guidelines', 'ai-polic...",This repository aims to map the ecosystem of a...,2.284940,1.0,1.0,4.246389
141,e6119864-3923-54a7-ba3f-e807f5fecc90,AI4Finance-Foundation/Awesome_AI4Finance,[],Resources,1.720333,1.0,1.0,4.316809
77,c3723afe-4e37-5864-be40-0b627e9048c7,ritchieng/the-incredible-pytorch,"['deep-learning', 'deep-learning-library', 'de...",The Incredible PyTorch: a curated list of tuto...,2.912900,1.0,1.0,4.369350
78,bebd9a86-0bcd-53d1-ab98-adc52d7e7435,daviddao/awful-ai,[],😈Awful AI is a curated list to track current s...,2.912900,1.0,1.0,4.369350
131,2acdeee5-13cf-5f1e-863f-cd13fdf49a7c,fuzzylabs/awesome-open-mlops,"['datascience', 'devops', 'infrastructure', 'm...",The Fuzzy Labs guide to the universe of open s...,1.841077,1.0,1.0,4.437553
165,be0b9bd1-71fb-5a90-a5f4-27b8e4bced8e,RUCAIBox/Awesome-RSPapers,[],Recommender System Papers,1.487906,1.0,1.0,4.463718
96,2f69d43c-7202-5a62-8090-a52993646860,yzhao062/anomaly-detection-resources,"['anomaly-detection', 'awesome', 'awesome-list...","Anomaly detection related books, papers, video...",2.314536,1.0,1.0,4.492295
55,f15b71c3-ddc5-57fc-9e8e-a1a1694c4cdd,ieshreya/Data-Science-Resources,"['computer-science', 'data-science', 'python',...",A curated collection of resources for learning...,3.915042,1.0,1.0,4.545490
85,eb532355-25eb-5125-8510-d513e06ada14,public-apis/public-apis,"['api', 'apis', 'dataset', 'development', 'fre...",A collective list of free APIs,2.787292,1.0,1.0,4.739835
60,9f1e40b6-cea9-5adc-8f7c-6fa075da171f,SylphAI-Inc/LLM-engineer-handbook,[],A curated list of Large Language Model resourc...,3.780353,1.0,1.0,4.747243
70,acc8f91d-bb82-5fbc-8354-176c040a4658,OrkoHunter/python-easter-eggs,"['easter-egg', 'python']",Curated list of all the easter eggs and hidden...,3.381498,1.0,1.0,5.072248
66,b4064311-8cad-57d6-a1f7-67f018512aab,youssefHosni/Data-Science-Interview-Questions-...,"['data-science', 'deep-learning', 'interview-q...",Curated list of data science interview questio...,3.466681,1.0,1.0,5.072248
90,18a771f3-14d4-5e68-9722-2d8ea672dc2b,Chalarangelo/30-seconds-of-code,"['astro', 'awesome-list', 'css', 'education', ...",Coding articles to level up your development s...,2.598227,1.0,1.0,5.196454
37,311bc521-1660-527c-9bce-8ce56dd740b1,bradtraversy/design-resources-for-developers,[],Curated list of design and UI resources from s...,4.636645,1.0,1.0,5.259805
73,38168b59-3a20-5146-9342-39ec2bdf0e6f,err0r500/foundational-knowledge-for-programmers,"['algorithms', 'algorithms-and-data-structures...",List of resources about foundational knowledge...,3.045541,1.0,1.0,5.309347
88,473ad8b3-d940-5953-ac6f-e8efb0c8a843,nikolaydubina/go-recipes,"['awesome', 'awesome-list', 'benchmarking', 'c...",🦩 Tools for Go projects,2.675083,1.0,1.0,5.350165
50,f2dceb52-c522-5393-bb1f-9f099d42a955,Gear61/Tech-Career-Growth-Learning-Resources-A...,[],"A curated, high-quality list of resources to l...",4.151118,1.0,1.0,5.557061
93,a13d1c12-d25f-5d58-b898-17986953e871,ashishps1/awesome-engineering-articles,"['ai', 'data-engineering', 'database', 'distri...",A curated collection of 300+ engineering blog ...,2.427097,1.0,1.0,5.588002
72,3844ced6-9f2e-5836-880a-6609ab4c2662,Renumics/awesome-anything2vec,['documentation-only'],Easy-to-use self-supervised representation lea...,3.055808,1.0,1.0,5.652284
57,2515bf02-c8c9-5ac6-bfcc-a3e0e71243ea,practical-tutorials/project-based-learning,"['beginner-project', 'cpp', 'golang', 'javascr...",Curated list of project-based tutorials,3.787718,1.0,1.0,5.681578
75,4eea0a1d-a518-519f-83f7-10d12fcf438e,cmhungsteve/Awesome-Transformer-Attention,"['attention-mechanism', 'attention-mechanisms'...",An ultimately comprehensive paper list of Visi...,2.986765,1.0,1.0,5.843244
61,42ded3bc-78b5-59f0-ab2d-6d89a6327514,EbookFoundation/free-programming-books,"['books', 'education', 'hacktoberfest', 'list'...",:books: Freely available programming books,3.776584,1.0,1.0,5.891860
41,1f324fdc-5690-5d3e-9ba1-0201ec59fdbb,f/prompts.chat,"['ai', 'artificial-intelligence', 'awesome-lis...","f.k.a. Awesome ChatGPT Prompts. Share, discove...",4.433145,1.0,1.0,5.936587
45,eea984e4-6c67-5330-91bf-f822aaa66ccb,ml-tooling/best-of-web-python,"['api', 'awesome', 'best-of', 'best-of-list', ...",🏆 A ranked list of awesome python libraries f...,4.335706,1.0,1.0,5.978804
44,88532728-a0cd-5d5f-8e54-68a9ab4a57b3,lukasmasuch/best-of-ml-python,"['automl', 'chatgpt', 'data-analysis', 'data-s...",🏆 A ranked list of awesome machine learning Py...,4.342355,1.0,1.0,5.985453
35,1d81f81c-e006-5b24-858c-b705b3148256,hemansnation/deep-learning-project-ideas,[],"Curated list of Machine Learning, NLP, Vision,...",4.806357,1.0,1.0,6.262808
48,ef38b20e-75e9-5fc3-b3a9-29e8aa43e489,ashishps1/awesome-leetcode-resources,"['algorithms', 'coding', 'data-structures', 'd...",Awesome LeetCode resources to learn Data Struc...,4.198517,1.0,1.0,6.377862
33,93032f3d-079a-5cb4-bbe7-c25e58755229,sickn33/antigravity-awesome-skills,"['agentic-skills', 'ai-agents', 'antigravity',...",The Ultimate Collection of 900+ Agentic Skills...,4.860525,1.0,1.0,6.391840
52,94dac6ef-e213-59f6-ba16-de5b0b284924,luspr/awesome-ml-courses,"['ai-courses', 'artificial-intelligence', 'dee...",Awesome free machine learning and AI courses w...,4.039392,1.0,1.0,6.511790
63,5ca2eefe-c9d3-52a2-9707-be82b04f31f2,vinta/awesome-python,"['awesome', 'collections', 'python', 'python-f...",An opinionated list of awesome Python framewor...,3.722586,1.0,1.0,6.808923
68,0a4d0333-f70c-5fb5-9ffc-870b6d7deab3,ugurkanates/awesome-real-world-rl,"['awesome', 'awesome-list', 'gans', 'imitation...",Great resources for making Reinforcement Learn...,3.413324,1.0,1.0,6.826648
67,a5238baf-54f5-5e58-9614-6b1ab9833fe3,codecrafters-io/build-your-own-x,"['awesome-list', 'free', 'programming', 'tutor...",Master programming by recreating your favorite...,3.414990,1.0,1.0,6.829981
98,a77fae33-5ac7-5d81-81ce-597eec09e2d8,grahamjenson/list_of_recommender_systems,[],A List of Recommender Systems and Resources,2.307851,1.0,1.0,6.923553
99,13093a80-91e5-545d-b796-c45544cddd8d,evanmiller/LLM-Reading-List,[],"LLM papers I'm reading, mostly on inference an...",2.307851,1.0,1.0,6.923553
74,7d7396ba-d332-50dc-96bb-0f3b68f3baaf,academic/awesome-datascience,"['analytics', 'awesome-list', 'data-mining', '...",:memo: An awesome Data Science repository to l...,2.992023,1.0,1.0,7.017026
47,bc96cfad-0378-51f9-824a-1caadcd9c0f2,jihoo-kim/awesome-RecSys,[],A curated list of awesome Recommender System (...,4.274755,1.0,1.0,7.444256
46,6fab82d3-9587-585f-9843-a04f0563079c,EthicalML/awesome-production-machine-learning,"['awesome', 'awesome-list', 'data-mining', 'de...",A curated list of awesome open source librarie...,4.328200,1.0,1.0,7.454203
64,842d61df-225c-5535-abf3-b30ca2083fa7,e2b-dev/awesome-ai-agents,"['agent', 'ai', 'artificial-intelligence', 'au...",A list of AI autonomous agents,3.585034,1.0,1.0,7.609411
32,c01c77d4-6cca-5a5c-91a8-e4a579cbfbbe,kilimchoi/engineering-blogs,"['engineering-blogs', 'lists', 'programming-bl...",A curated list of engineering blogs,4.925609,1.0,1.0,7.629620
31,4ebf2d93-5068-5668-bf76-530789fa6366,awesomedata/awesome-public-datasets,"['aaron-swartz', 'awesome-public-datasets', 'd...",A topic-centric list of HQ open datasets.,4.948167,1.0,1.0,7.779855
54,3ad6e195-485a-5744-a2b2-13a6b40bce03,ossu/computer-science,"['awesome-list', 'computer-science', 'courses'...",🎓 Path to a free self-taught education in Comp...,3.946703,1.0,1.0,7.893405
40,6ee58ab7-a21a-5804-8fe0-2580eda75758,Renumics/awesome-open-data-centric-ai,"['active-learning', 'awesome-list', 'bias-dete...",Curated list of open source tooling for data-c...,4.542036,1.0,1.0,8.035331
42,7618ee28-b57f-59c0-b874-20bd20063acc,ronikobrosly/awesome-data-leadership,[],"A curated list of awesome posts, videos, and a...",4.423919,1.0,1.0,8.071146
65,86032f91-6cb3-54ba-85cd-35980dee5250,TsinghuaC3I/Awesome-RL-for-LRMs,"['awesome-list', 'deepseek-r1', 'llm', 'lrm', ...",A Survey of Reinforcement Learning for Large R...,3.575561,1.0,1.0,8.097518
10,22095ee8-aa17-5edf-8178-c1848c396ab5,EthicalML/awesome-annual-reviews-and-trends,[],A curated list of awesome year-in-review and a...,6.203630,1.0,1.0,8.102716
30,9369c17d-24eb-5696-a2a6-f992e65cb2bb,MarcSkovMadsen/awesome-streamlit,"['analytics', 'apps', 'awesome-list', 'data', ...",The purpose of this project is to share knowle...,5.082046,1.0,1.0,8.320680
49,c9cd2396-19b4-5049-8fde-1a44cb819c3a,online-ml/awesome-online-machine-learning,"['awesome', 'awesome-list', 'machine-learning'...",:bookmark_tabs: Online machine learning resources,4.193659,1.0,1.0,8.387319
39,5f8d0d08-bd20-5cf8-bf9b-fd92ec1d114e,cloudcommunity/Free-Certifications,"['awesome', 'awesome-list', 'awesome-lists', '...",A curated list of free courses with certificat...,4.581464,1.0,1.0,8.448971
26,d1b21161-09d6-5843-85e9-a6a7aadce77f,r0f1/datascience,"['artificial-intelligence', 'awesome', 'awesom...",Curated list of Python resources for data scie...,5.218129,1.0,1.0,8.649709
51,a29663e6-963e-5282-8c9d-24f6e4dba82a,aikorea/awesome-rl,[],Reinforcement learning resources curated,4.135534,1.0,1.0,8.653811
36,c64ddcff-35f6-5f3e-b957-23481ef7153c,NirantK/awesome-project-ideas,"['awesome', 'awesome-list', 'classification', ...","Curated list of Machine Learning, NLP, Vision,...",4.761151,1.0,1.0,8.688828
27,f51eac8f-0fcc-5db4-ac5e-d6dfdeb617ca,josephmisiti/awesome-machine-learning,[],A curated list of awesome Machine Learning fra...,5.211991,1.0,1.0,8.708815
29,c8a559e9-1498-55f9-b384-487209381fba,madd86/awesome-system-design,"['distributed-systems', 'hadoop-ecosystem', 'i...",A curated list of awesome System Design (A.K.A...,5.099374,1.0,1.0,8.708815
43,c627ee35-96f4-5493-b366-d96e89f8b62c,lauris/awesome-scala,"['awesome', 'awesome-list', 'scala', 'scala-li...",A community driven list of useful Scala librar...,4.361296,1.0,1.0,8.722592
38,93af64dd-5418-57bf-82fd-2ff283a554f4,azminewasi/Curated-Reinforcement-Learning-Reso...,"['deep-learning', 'deep-reinforcement-learning...",Reinforcement learning is a machine learning t...,4.602807,1.0,1.0,9.091021
34,256a85ca-e07b-58e5-ac35-91db7fc7465f,ai-boost/awesome-prompts,"['awesome', 'awesome-list', 'chatgpt', 'gpt4',...",Curated list of chatgpt prompts from the top-r...,4.817416,1.0,1.0,9.231098
23,7dbc56bf-b0c5-5b88-a171-3f676b61191a,youngwookim/awesome-hadoop,[],A curated list of amazingly awesome Hadoop and...,5.397048,1.0,1.0,9.277819
24,e2abc867-298f-5ee6-bb47-4a200494aab7,pawl/awesome-etl,[],"A curated list of awesome ETL frameworks, libr...",5.372819,1.0,1.0,9.535966
18,bb89d0c8-db30-5379-9b8d-f4b0f5dd3a4f,brianspiering/awesome-deep-rl,[],A curated list of awesome Deep Reinforcement L...,5.733269,1.0,1.0,9.535966
12,f283f1aa-2254-5605-9630-80c59c07024b,ramitsurana/awesome-kubernetes,"['aws', 'azure', 'books', 'cloud-providers', '...",A curated list for awesome kubernetes sources ...,6.136012,1.0,1.0,9.535966
17,551634f3-7fc6-5b31-a676-b693e59d648c,theanalyst/awesome-distributed-systems,"['architecture', 'consensus', 'distributed-sys...",A curated list to learn about distributed systems,5.804758,1.0,1.0,9.576292
20,4060f165-6902-53bc-8e6d-60217fda3ea2,costezki/awesome-nlprojects,"['awersome-list', 'machine-learning', 'natural...",List of projects related to Natural Language P...,5.597083,1.0,1.0,9.620706
28,3691b379-d8b0-53b9-9375-a95dfb68a5ad,n2cholas/awesome-jax,"['autograd', 'awesome', 'awesome-list', 'deep-...",JAX - A curated list of resources https://gith...,5.104913,1.0,1.0,9.755164
16,42af1a59-3545-55cf-a2f8-6165e4edf4ec,pabloem/awesome-beam,[],A curated list of awesome resources for Apache...,5.834331,1.0,1.0,9.823368
15,5bab555b-9ee4-500e-8f8a-738d2247825b,mauhai/awesome-jupyterlab,"['awesome', 'collections', 'jupyterlab', 'jupy...",A curated list of awesome JupyterLab extension...,5.893960,1.0,1.0,9.823368
19,8ca301dc-cd7d-5502-a5a8-4f9a88db7cad,Palashio/awesome-libra,[],A curated list of all things related to libra.,5.604686,1.0,1.0,10.145296
22,7fddb7a8-8ca3-56f4-bdcc-9088fd1315f0,travisvn/awesome-claude-skills,"['agentic-coding', 'anthropic', 'awesome', 'aw...","A curated list of awesome Claude Skills, resou...",5.435575,1.0,1.0,10.215125
69,3b441a31-8b40-5e98-b51b-9d3a374570a1,Engineer1999/A-Curated-List-of-ML-System-Desig...,[],This repository contains a curated collection ...,3.407397,1.0,1.0,10.222190
13,102480a9-60d3-56ee-b142-3573a3b9c9a8,visenger/awesome-mlops,"['ai', 'data-science', 'devops', 'engineering'...",A curated list of references for MLOps,6.003039,1.0,1.0,10.508368
21,4a61394a-9995-50eb-a77a-dacd5490ed31,kengz/awesome-deep-rl,"['awesome-list', 'deep-reinforcement-learning'...",A curated list of awesome Deep Reinforcement L...,5.460817,1.0,1.0,10.535618
25,1dbbd6f0-01c6-54b0-bf6c-618f876ea524,creyesp/Awesome-recsys,"['awesome-list', 'deep-learning', 'machine-lea...",Curated list of recommnedation system topics,5.328973,1.0,1.0,10.562084
14,b5f0b508-114b-5d97-8c31-36b3b190a4da,DovAmir/awesome-design-patterns,"['architecture', 'awesome', 'awesome-list', 'c...",A curated list of software and architecture re...,5.968225,1.0,1.0,10.940893

In [53]:
comparison.isna().sum()

id                      0
repo                    0
topics                  0
description            62
score_v1                0
is_a_curated_list    1844
is_not_a_library     1844
score_v2                0
dtype: int64

In [58]:
# load next version of data
with open("../data/cached/github_data2.pkl", "rb") as f:
    starred_repo_data = pickle.load(f)

In [59]:
df2 = pd.DataFrame(starred_repo_data)
df2.head()

,repo,description,topics,stars,language,url,doc_source,docs
0,laurynasjs/personalized-recommendations-at-scale,None,[],2,Jupyter Notebook,https://github.com/laurynasjs/personalized-rec...,readme,"[{'name': 'README.md', 'path': 'README.md', 's..."
1,sumitsidana/corise_personalized_recommendation...,None,[],2,Jupyter Notebook,https://github.com/sumitsidana/corise_personal...,None,[]
2,hrjoshi28/corise-recsys,personalized-recommendations-at-scale,[],1,Jupyter Notebook,https://github.com/hrjoshi28/corise-recsys,readme,"[{'name': 'README.md', 'path': 'README.md', 's..."
3,tusharagarwal25/corise-Personalized-Recommenda...,None,[],1,Jupyter Notebook,https://github.com/tusharagarwal25/corise-Pers...,None,[]
4,yudhiesh/corise-Personalized-Recommendations-a...,Course work for the co:rise course Personalize...,[],2,Jupyter Notebook,https://github.com/yudhiesh/corise-Personalize...,None,[]

In [64]:
df2['docs']

0       [{'name': 'README.md', 'path': 'README.md', 's...
1                                                      []
2       [{'name': 'README.md', 'path': 'README.md', 's...
3                                                      []
4                                                      []
                              ...
2080    [{'name': 'README.md', 'path': 'README.md', 's...
2081    [{'name': 'README.rst', 'path': 'README.rst', ...
2082    [{'name': 'README.md', 'path': 'README.md', 's...
2083    [{'name': 'README.md', 'path': 'README.md', 's...
2084    [{'name': 'README.md', 'path': 'README.md', 's...
Name: docs, Length: 2085, dtype: object

In [65]:
def extract_url_count(docs_list):
    if not isinstance(docs_list, list) or len(docs_list) == 0:
        return None
    counts = [doc.get('url_count') for doc in docs_list if doc.get('url_count') is not None]
    return sum(counts) if counts else None

In [66]:
df2['url_count'] = df2['docs'].apply(extract_url_count)

In [67]:
df2.head()

,repo,description,topics,stars,language,url,doc_source,docs,url_count
0,laurynasjs/personalized-recommendations-at-scale,None,[],2,Jupyter Notebook,https://github.com/laurynasjs/personalized-rec...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",0.0
1,sumitsidana/corise_personalized_recommendation...,None,[],2,Jupyter Notebook,https://github.com/sumitsidana/corise_personal...,None,[],NaN
2,hrjoshi28/corise-recsys,personalized-recommendations-at-scale,[],1,Jupyter Notebook,https://github.com/hrjoshi28/corise-recsys,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",0.0
3,tusharagarwal25/corise-Personalized-Recommenda...,None,[],1,Jupyter Notebook,https://github.com/tusharagarwal25/corise-Pers...,None,[],NaN
4,yudhiesh/corise-Personalized-Recommendations-a...,Course work for the co:rise course Personalize...,[],2,Jupyter Notebook,https://github.com/yudhiesh/corise-Personalize...,None,[],NaN

In [68]:
df2['id'] = df2['repo'].apply(repo_to_uuid)
df2.head()

,repo,description,topics,stars,language,url,doc_source,docs,url_count,id
0,laurynasjs/personalized-recommendations-at-scale,None,[],2,Jupyter Notebook,https://github.com/laurynasjs/personalized-rec...,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",0.0,5bc8fab8-25ed-580d-b51a-0c1cda593ec9
1,sumitsidana/corise_personalized_recommendation...,None,[],2,Jupyter Notebook,https://github.com/sumitsidana/corise_personal...,None,[],NaN,e2758043-5e0b-50ee-8be2-5296c76fbe36
2,hrjoshi28/corise-recsys,personalized-recommendations-at-scale,[],1,Jupyter Notebook,https://github.com/hrjoshi28/corise-recsys,readme,"[{'name': 'README.md', 'path': 'README.md', 's...",0.0,89169455-9ef8-56ea-951e-f5389db2dc49
3,tusharagarwal25/corise-Personalized-Recommenda...,None,[],1,Jupyter Notebook,https://github.com/tusharagarwal25/corise-Pers...,None,[],NaN,b2bc8a01-a1bb-54a7-99fd-8b398bb4a3d7
4,yudhiesh/corise-Personalized-Recommendations-a...,Course work for the co:rise course Personalize...,[],2,Jupyter Notebook,https://github.com/yudhiesh/corise-Personalize...,None,[],NaN,20cc77ee-c042-52dc-bc36-da25eb309b8a

In [69]:
comparison2 = (
    results_ann[['id', 'repo', 'topics', 'description', 'score', 'is_a_curated_list', 'is_not_a_library']]
    .merge(results2[['id', 'score']],
           on='id',
           suffixes=('_v1', '_v2')
           )
    .merge(df2[['id', 'url_count']], on='id')
)

In [70]:
comparison2.head()

,id,repo,topics,description,score_v1,is_a_curated_list,is_not_a_library,score_v2,url_count
0,6a6a505a-45ec-5402-b338-aea20a0047fd,jnv/lists,"['awesome', 'awesome-list', 'curated-lists', '...",The definitive list of lists (of lists) curate...,8.930841,1.0,1.0,20.959242,1797.0
1,1dbd0153-427b-5c52-9793-faa45ae6877e,zudochkin/awesome-newsletters,"['awesome', 'awesome-list', 'email', 'email-ne...",A list of amazing Newsletters,7.235460,1.0,1.0,11.148891,339.0
2,62762741-11e6-5e42-9d12-8e8101f7469d,ddotta/awesome-polars,"['awesome', 'awesome-list', 'collection', 'cur...","A curated list of Polars talks, tools, example...",7.233369,1.0,1.0,14.590599,649.0
3,9647593c-9b19-5b13-b2ef-744125cd6f1e,aporia-ai/mlops.toys,"['awesome', 'awesome-list', 'data-science', 'l...","🎲 A curated list of MLOps projects, tools and ...",6.951973,1.0,1.0,12.115523,5.0
4,7636125b-0534-500b-b0b9-22717eeefb11,awesomelistsio/awesome-reinforcement-learning,"['awesome', 'awesome-list', 'awesome-lists', '...","A curated list of awesome frameworks, librarie...",6.851551,1.0,1.0,12.145926,52.0

In [71]:
comparison2.query('is_a_curated_list == 1').sort_values('score_v2', ascending=True)

,id,repo,topics,description,score_v1,is_a_curated_list,is_not_a_library,score_v2,url_count
203,688f34a1-1e63-5699-bfd4-fc39eda17a28,eugeneyan/applied-ml,"['applied-data-science', 'applied-machine-lear...",📚 Papers & tech blogs by companies sharing the...,1.019706,1.0,1.0,1.019706,779.0
192,78a29dca-4c58-56a3-b009-ec50a982cb0f,Nyandwi/machine_learning_complete,"['computer-vision', 'data-analysis', 'data-sci...",A comprehensive machine learning repository co...,1.140272,1.0,0.0,1.140272,115.0
187,8608f534-a0d4-598b-9eba-fd1c909d0b24,Rishabh-creator601/Books,"['computer-vision', 'cpp', 'deep-learning', 'd...",Books / PDFS / EPUBS for different fields of p...,1.201308,1.0,1.0,1.201308,188.0
184,1016bca9-95ad-5e1b-b8c8-a5163f7da5e9,dair-ai/ML-Papers-Explained,[],Explanation to key concepts in ML,1.225630,1.0,1.0,1.225630,588.0
152,7144519b-186a-5bd9-bafb-936670346a95,chihming/competitive-recsys,"['collaborative-filtering', 'recommendation-al...",A collection of resources for Recommender Syst...,1.603412,1.0,1.0,1.603412,146.0
144,670b5771-2b9d-5720-b1e7-2b59a6705fda,NirDiamant/RAG_Techniques,"['ai', 'langchain', 'llama-index', 'llm', 'llm...",This repository showcases various advanced tec...,1.714251,1.0,1.0,1.714251,322.0
136,3f995872-441f-5fde-9635-c13fcc7808c5,CodeCutTech/Data-science,"['articles', 'artificial-intelligence', 'data-...",Collection of useful data science topics along...,1.759038,1.0,1.0,1.759038,68.0
134,caf93575-2b5f-5b9e-91f4-e0c348a9431d,ashishps1/learn-ai-engineering,"['agentic-ai', 'agents', 'ai', 'deep-learning'...",Learn AI and LLMs from scratch using free reso...,1.796410,1.0,1.0,1.796410,114.0
109,6f9c8926-52e0-51ee-8f70-2088c093cb6b,AkashSingh3031/The-Complete-FAANG-Preparation,"['algorithms', 'aptitude', 'collaborate', 'com...","Dive into this repository, a comprehensive res...",2.107226,1.0,1.0,2.107226,846.0
107,61250239-b16b-53bc-af8f-7de5a9e2e3b3,realpython/discover-flask,[],Full Stack Web Development with Flask.,2.134127,1.0,1.0,2.134127,75.0
166,b42a260b-1230-5e1c-9882-9af80604d64c,deep-learning-drizzle/deep-learning-drizzle.gi...,"['computer-vision', 'deep-learning', 'deep-neu...",webpage for maintaining the list of openly ava...,1.487752,1.0,1.0,2.231628,NaN
159,098019fa-0920-5e20-a1ec-6c5407c76fdd,dbohdan/structured-text-tools,"['awk', 'cli', 'configuration-file', 'conversi...",A list of command-line tools for manipulating ...,1.563470,1.0,1.0,2.345205,353.0
153,601a986f-14da-5723-9df0-c827a8fdb834,SkalskiP/courses,"['computer-vision', 'deep-learning', 'deep-neu...",This repository is a curated collection of lin...,1.602069,1.0,1.0,2.349327,38.0
91,c11cf7dc-6e51-56ca-98d3-916f8f28f494,thubZ09/vision-language-model-research,"['computer-vision', 'deep-learning', 'machine-...",Hub for researchers exploring VLMs and Multimo...,2.524721,1.0,1.0,2.524721,177.0
198,95b561fd-325e-5cdf-b5a5-0aa81166fde4,guyulongcs/Awesome-Deep-Learning-Papers-for-Se...,"['advertising', 'ctr', 'cvr', 'deep-learning',...",Awesome Deep Learning papers for industrial Se...,1.071771,1.0,1.0,2.579466,528.0
139,577005be-d457-5cec-8e92-d9f54bba6dda,FavioVazquez/ds-cheatsheets,"['cheatsheet', 'datascience', 'jupyter', 'prog...",List of Data Science Cheatsheets to rule the w...,1.740648,1.0,1.0,2.610971,292.0
138,cf1ce42f-d5fa-50f1-b23d-7be1ed94f956,Developer-Y/cs-video-courses,"['algorithms', 'bioinformatics', 'computationa...",List of Computer Science courses with video le...,1.740648,1.0,1.0,2.610971,1707.0
87,19a49185-4af6-55c9-b9db-5545fab31c47,alexeygrigorev/data-science-interviews,"['data-science', 'data-science-interviews', 'i...",Data science interview questions and answers,2.713821,1.0,1.0,2.713821,7.0
86,98da642a-4a2e-566c-9871-792ab014f9f7,openai/spinningup,[],An educational resource to help anyone learn d...,2.767177,1.0,1.0,2.767177,8.0
80,94bb60a3-7135-52e4-af3c-e448f59ad48a,pysemtec/semantic-python-overview,"['collection', 'community-driven', 'datalog', ...",(subjective) overview of projects which are re...,2.839143,1.0,1.0,2.839143,142.0
76,3efbbb6e-2604-5ea0-add9-673cf7c23d19,ashishpatel26/500-AI-Machine-learning-Deep-lea...,"['artificial-intelligence', 'artificial-intell...",500 AI Machine learning Deep learning Computer...,2.912994,1.0,1.0,2.912994,106.0
151,5e5cc497-50c5-522b-9662-8e2154a37a17,rougier/ML-Recipes,"['algorithm', 'awesome', 'machine-learning', '...",A collection of stand-alone Python machine lea...,1.607495,1.0,1.0,3.214989,13.0
71,39135dff-5858-5b4a-bc85-5d732ecf059e,bmorelli25/Become-A-Full-Stack-Web-Developer,[],Free resources for learning Full Stack Web Dev...,3.222230,1.0,1.0,3.222230,253.0
116,cd18a81d-97b5-5176-ad5c-fbdcc0235ae7,zzsza/Awesome-Mobility-Machine-Learning-Contents,[],Machine Learning / Deep Learning Contents in M...,2.028187,1.0,1.0,3.452000,132.0
174,99dc20b9-4672-5286-a491-178fa3ae8764,ashishps1/awesome-low-level-design,"['awesome', 'design-patterns', 'interview', 'i...",Learn Low Level Design (LLD) and prepare for i...,1.359674,1.0,1.0,3.454376,82.0
177,597e6247-805f-51fd-a4cd-f1b5b8a5f592,ashishps1/awesome-system-design-resources,"['awesome', 'backend', 'computer-science', 'di...",Learn System Design concepts and prepare for i...,1.310457,1.0,1.0,3.454376,142.0
190,c59e4658-780b-5d49-a43c-3a93724cb06f,AI-Maker-Space/Awesome-AIM-Index,[],An index of all of our weekly concepts + code ...,1.151458,1.0,1.0,3.454376,504.0
135,c4a114b7-216f-5310-95c4-d83a94d3c096,Plankson/awesome-explainable-reinforcement-lea...,"['explainable-reinforcement-learning', 'reinfo...",A Survey on Explainable Reinforcement Learning...,1.775933,1.0,1.0,3.766495,217.0
81,91abb07c-fa69-53c1-8e87-32235ac4a2a4,LincolnBurrows2017/gauss-awesome-recommender-s...,[],gauss-awesome-recommender-system-engine,2.823666,1.0,1.0,3.768163,38.0
84,4ca2aae5-4be8-5cf2-b68f-8344c681b41c,louisfb01/best_AI_papers_2021,"['2021', 'ai', 'artificial-intelligence', 'art...",A curated list of the latest breakthroughs in...,2.805305,1.0,1.0,3.837554,232.0
103,7b52fab1-e7fa-5b1a-ae7d-31fc62e25a62,papers-we-love/papers-we-love,"['awesome', 'computer-science', 'meetup', 'pap...",Papers from the computer science community to ...,2.212077,1.0,1.0,3.891761,41.0
150,7aed6213-3b9f-5c56-a36b-bb5346e9d982,rguo12/awesome-causality-data,[],A data index for learning causality.,1.617253,1.0,1.0,3.894714,25.0
170,f379036a-6b94-566f-ba08-a66a782e920d,rguo12/awesome-causality-algorithms,"['awesome', 'baselines', 'causal-inference', '...",An index of algorithms for learning causality ...,1.409074,1.0,1.0,3.894714,254.0
105,0d7e29c6-c8c5-5cf6-b579-0447db064f04,Bogdanp/awesome-advent-of-code,"['advent-of-code', 'advent-of-code-2018', 'adv...",A collection of awesome resources related to t...,2.146670,1.0,1.0,4.151410,299.0
58,0044d05a-82a2-5871-afac-93f59c2a2956,yangshun/tech-interview-handbook,"['algorithm', 'algorithm-interview', 'algorith...",Curated coding interview preparation materials...,3.786222,1.0,1.0,4.194734,57.0
101,c1669d9b-ca69-506a-b759-17a262af4ad8,EthicalML/awesome-artificial-intelligence-regu...,"['ai', 'ai-ethics', 'ai-guidelines', 'ai-polic...",This repository aims to map the ecosystem of a...,2.284940,1.0,1.0,4.246389,148.0
141,e6119864-3923-54a7-ba3f-e807f5fecc90,AI4Finance-Foundation/Awesome_AI4Finance,[],Resources,1.720333,1.0,1.0,4.316809,39.0
77,c3723afe-4e37-5864-be40-0b627e9048c7,ritchieng/the-incredible-pytorch,"['deep-learning', 'deep-learning-library', 'de...",The Incredible PyTorch: a curated list of tuto...,2.912900,1.0,1.0,4.369350,545.0
78,bebd9a86-0bcd-53d1-ab98-adc52d7e7435,daviddao/awful-ai,[],😈Awful AI is a curated list to track current s...,2.912900,1.0,1.0,4.369350,206.0
131,2acdeee5-13cf-5f1e-863f-cd13fdf49a7c,fuzzylabs/awesome-open-mlops,"['datascience', 'devops', 'infrastructure', 'm...",The Fuzzy Labs guide to the universe of open s...,1.841077,1.0,1.0,4.437553,69.0
165,be0b9bd1-71fb-5a90-a5f4-27b8e4bced8e,RUCAIBox/Awesome-RSPapers,[],Recommender System Papers,1.487906,1.0,1.0,4.463718,19.0
96,2f69d43c-7202-5a62-8090-a52993646860,yzhao062/anomaly-detection-resources,"['anomaly-detection', 'awesome', 'awesome-list...","Anomaly detection related books, papers, video...",2.314536,1.0,1.0,4.492295,280.0
55,f15b71c3-ddc5-57fc-9e8e-a1a1694c4cdd,ieshreya/Data-Science-Resources,"['computer-science', 'data-science', 'python',...",A curated collection of resources for learning...,3.915042,1.0,1.0,4.545490,135.0
85,eb532355-25eb-5125-8510-d513e06ada14,public-apis/public-apis,"['api', 'apis', 'dataset', 'development', 'fre...",A collective list of free APIs,2.787292,1.0,1.0,4.739835,1460.0
60,9f1e40b6-cea9-5adc-8f7c-6fa075da171f,SylphAI-Inc/LLM-engineer-handbook,[],A curated list of Large Language Model resourc...,3.780353,1.0,1.0,4.747243,112.0
70,acc8f91d-bb82-5fbc-8354-176c040a4658,OrkoHunter/python-easter-eggs,"['easter-egg', 'python']",Curated list of all the easter eggs and hidden...,3.381498,1.0,1.0,5.072248,11.0
66,b4064311-8cad-57d6-a1f7-67f018512aab,youssefHosni/Data-Science-Interview-Questions-...,"['data-science', 'deep-learning', 'interview-q...",Curated list of data science interview questio...,3.466681,1.0,1.0,5.072248,30.0
90,18a771f3-14d4-5e68-9722-2d8ea672dc2b,Chalarangelo/30-seconds-of-code,"['astro', 'awesome-list', 'css', 'education', ...",Coding articles to level up your development s...,2.598227,1.0,1.0,5.196454,11.0
37,311bc521-1660-527c-9bce-8ce56dd740b1,bradtraversy/design-resources-for-developers,[],Curated list of design and UI resources from s...,4.636645,1.0,1.0,5.259805,1099.0
73,38168b59-3a20-5146-9342-39ec2bdf0e6f,err0r500/foundational-knowledge-for-programmers,"['algorithms', 'algorithms-and-data-structures...",List of resources about foundational knowledge...,3.045541,1.0,1.0,5.309347,56.0
88,473ad8b3-d940-5953-ac6f-e8efb0c8a843,nikolaydubina/go-recipes,"['awesome', 'awesome-list', 'benchmarking', 'c...",🦩 Tools for Go projects,2.675083,1.0,1.0,5.350165,514.0
50,f2dceb52-c522-5393-bb1f-9f099d42a955,Gear61/Tech-Career-Growth-Learning-Resources-A...,[],"A curated, high-quality list of resources to l...",4.151118,1.0,1.0,5.557061,70.0
93,a13d1c12-d25f-5d58-b898-17986953e871,ashishps1/awesome-engineering-articles,"['ai', 'data-engineering', 'database', 'distri...",A curated collection of 300+ engineering blog ...,2.427097,1.0,1.0,5.588002,382.0
72,3844ced6-9f2e-5836-880a-6609ab4c2662,Renumics/awesome-anything2vec,['documentation-only'],Easy-to-use self-supervised representation lea...,3.055808,1.0,1.0,5.652284,125.0
57,2515bf02-c8c9-5ac6-bfcc-a3e0e71243ea,practical-tutorials/project-based-learning,"['beginner-project', 'cpp', 'golang', 'javascr...",Curated list of project-based tutorials,3.787718,1.0,1.0,5.681578,458.0
75,4eea0a1d-a518-519f-83f7-10d12fcf438e,cmhungsteve/Awesome-Transformer-Attention,"['attention-mechanism', 'attention-mechanisms'...",An ultimately comprehensive paper list of Visi...,2.986765,1.0,1.0,5.843244,3531.0
61,42ded3bc-78b5-59f0-ab2d-6d89a6327514,EbookFoundation/free-programming-books,"['books', 'education', 'hacktoberfest', 'list'...",:books: Freely available programming books,3.776584,1.0,1.0,5.891860,49.0
41,1f324fdc-5690-5d3e-9ba1-0201ec59fdbb,f/prompts.chat,"['ai', 'artificial-intelligence', 'awesome-lis...","f.k.a. Awesome ChatGPT Prompts. Share, discove...",4.433145,1.0,1.0,5.936587,70.0
45,eea984e4-6c67-5330-91bf-f822aaa66ccb,ml-tooling/best-of-web-python,"['api', 'awesome', 'best-of', 'best-of-list', ...",🏆 A ranked list of awesome python libraries f...,4.335706,1.0,1.0,5.978804,2672.0
44,88532728-a0cd-5d5f-8e54-68a9ab4a57b3,lukasmasuch/best-of-ml-python,"['automl', 'chatgpt', 'data-analysis', 'data-s...",🏆 A ranked list of awesome machine learning Py...,4.342355,1.0,1.0,5.985453,3899.0
35,1d81f81c-e006-5b24-858c-b705b3148256,hemansnation/deep-learning-project-ideas,[],"Curated list of Machine Learning, NLP, Vision,...",4.806357,1.0,1.0,6.262808,67.0
48,ef38b20e-75e9-5fc3-b3a9-29e8aa43e489,ashishps1/awesome-leetcode-resources,"['algorithms', 'coding', 'data-structures', 'd...",Awesome LeetCode resources to learn Data Struc...,4.198517,1.0,1.0,6.377862,81.0
33,93032f3d-079a-5cb4-bbe7-c25e58755229,sickn33/antigravity-awesome-skills,"['agentic-skills', 'ai-agents', 'antigravity',...",The Ultimate Collection of 900+ Agentic Skills...,4.860525,1.0,1.0,6.391840,172.0
52,94dac6ef-e213-59f6-ba16-de5b0b284924,luspr/awesome-ml-courses,"['ai-courses', 'artificial-intelligence', 'dee...",Awesome free machine learning and AI courses w...,4.039392,1.0,1.0,6.511790,56.0
63,5ca2eefe-c9d3-52a2-9707-be82b04f31f2,vinta/awesome-python,"['awesome', 'collections', 'python', 'python-f...",An opinionated list of awesome Python framewor...,3.722586,1.0,1.0,6.808923,673.0
68,0a4d0333-f70c-5fb5-9ffc-870b6d7deab3,ugurkanates/awesome-real-world-rl,"['awesome', 'awesome-list', 'gans', 'imitation...",Great resources for making Reinforcement Learn...,3.413324,1.0,1.0,6.826648,78.0
67,a5238baf-54f5-5e58-9614-6b1ab9833fe3,codecrafters-io/build-your-own-x,"['awesome-list', 'free', 'programming', 'tutor...",Master programming by recreating your favorite...,3.414990,1.0,1.0,6.829981,368.0
98,a77fae33-5ac7-5d81-81ce-597eec09e2d8,grahamjenson/list_of_recommender_systems,[],A List of Recommender Systems and Resources,2.307851,1.0,1.0,6.923553,140.0
99,13093a80-91e5-545d-b796-c45544cddd8d,evanmiller/LLM-Reading-List,[],"LLM papers I'm reading, mostly on inference an...",2.307851,1.0,1.0,6.923553,68.0
74,7d7396ba-d332-50dc-96bb-0f3b68f3baaf,academic/awesome-datascience,"['analytics', 'awesome-list', 'data-mining', '...",:memo: An awesome Data Science repository to l...,2.992023,1.0,1.0,7.017026,951.0
47,bc96cfad-0378-51f9-824a-1caadcd9c0f2,jihoo-kim/awesome-RecSys,[],A curated list of awesome Recommender System (...,4.274755,1.0,1.0,7.444256,137.0
46,6fab82d3-9587-585f-9843-a04f0563079c,EthicalML/awesome-production-machine-learning,"['awesome', 'awesome-list', 'data-mining', 'de...",A curated list of awesome open source librarie...,4.328200,1.0,1.0,7.454203,1068.0
64,842d61df-225c-5535-abf3-b30ca2083fa7,e2b-dev/awesome-ai-agents,"['agent', 'ai', 'artificial-intelligence', 'au...",A list of AI autonomous agents,3.585034,1.0,1.0,7.609411,1192.0
32,c01c77d4-6cca-5a5c-91a8-e4a579cbfbbe,kilimchoi/engineering-blogs,"['engineering-blogs', 'lists', 'programming-bl...",A curated list of engineering blogs,4.925609,1.0,1.0,7.629620,452.0
31,4ebf2d93-5068-5668-bf76-530789fa6366,awesomedata/awesome-public-datasets,"['aaron-swartz', 'awesome-public-datasets', 'd...",A topic-centric list of HQ open datasets.,4.948167,1.0,1.0,7.779855,1621.0
54,3ad6e195-485a-5744-a2b2-13a6b40bce03,ossu/computer-science,"['awesome-list', 'computer-science', 'courses'...",🎓 Path to a free self-taught education in Comp...,3.946703,1.0,1.0,7.893405,152.0
40,6ee58ab7-a21a-5804-8fe0-2580eda75758,Renumics/awesome-open-data-centric-ai,"['active-learning', 'awesome-list', 'bias-dete...",Curated list of open source tooling for data-c...,4.542036,1.0,1.0,8.035331,294.0
42,7618ee28-b57f-59c0-b874-20bd20063acc,ronikobrosly/awesome-data-leadership,[],"A curated list of awesome posts, videos, and a...",4.423919,1.0,1.0,8.071146,343.0
65,86032f91-6cb3-54ba-85cd-35980dee5250,TsinghuaC3I/Awesome-RL-for-LRMs,"['awesome-list', 'deepseek-r1', 'llm', 'lrm', ...",A Survey of Reinforcement Learning for Large R...,3.575561,1.0,1.0,8.097518,1850.0
10,22095ee8-aa17-5edf-8178-c1848c396ab5,EthicalML/awesome-annual-reviews-and-trends,[],A curated list of awesome year-in-review and a...,6.203630,1.0,1.0,8.102716,44.0
30,9369c17d-24eb-5696-a2a6-f992e65cb2bb,MarcSkovMadsen/awesome-streamlit,"['analytics', 'apps', 'awesome-list', 'data', ...",The purpose of this project is to share knowle...,5.082046,1.0,1.0,8.320680,182.0
49,c9cd2396-19b4-5049-8fde-1a44cb819c3a,online-ml/awesome-online-machine-learning,"['awesome', 'awesome-list', 'machine-learning'...",:bookmark_tabs: Online machine learning resources,4.193659,1.0,1.0,8.387319,117.0
39,5f8d0d08-bd20-5cf8-bf9b-fd92ec1d114e,cloudcommunity/Free-Certifications,"['awesome', 'awesome-list', 'awesome-lists', '...",A curated list of free courses with certificat...,4.581464,1.0,1.0,8.448971,207.0
26,d1b21161-09d6-5843-85e9-a6a7aadce77f,r0f1/datascience,"['artificial-intelligence', 'awesome', 'awesom...",Curated list of Python resources for data scie...,5.218129,1.0,1.0,8.649709,1259.0
51,a29663e6-963e-5282-8c9d-24f6e4dba82a,aikorea/awesome-rl,[],Reinforcement learning resources curated,4.135534,1.0,1.0,8.653811,242.0
36,c64ddcff-35f6-5f3e-b957-23481ef7153c,NirantK/awesome-project-ideas,"['awesome', 'awesome-list', 'classification', ...","Curated list of Machine Learning, NLP, Vision,...",4.761151,1.0,1.0,8.688828,67.0
27,f51eac8f-0fcc-5db4-ac5e-d6dfdeb617ca,josephmisiti/awesome-machine-learning,[],A curated list of awesome Machine Learning fra...,5.211991,1.0,1.0,8.708815,1291.0
29,c8a559e9-1498-55f9-b384-487209381fba,madd86/awesome-system-design,"['distributed-systems', 'hadoop-ecosystem', 'i...",A curated list of awesome System Design (A.K.A...,5.099374,1.0,1.0,8.708815,126.0
43,c627ee35-96f4-5493-b366-d96e89f8b62c,lauris/awesome-scala,"['awesome', 'awesome-list', 'scala', 'scala-li...",A community driven list of useful Scala librar...,4.361296,1.0,1.0,8.722592,875.0
38,93af64dd-5418-57bf-82fd-2ff283a554f4,azminewasi/Curated-Reinforcement-Learning-Reso...,"['deep-learning', 'deep-reinforcement-learning...",Reinforcement learning is a machine learning t...,4.602807,1.0,1.0,9.091021,27.0
34,256a85ca-e07b-58e5-ac35-91db7fc7465f,ai-boost/awesome-prompts,"['awesome', 'awesome-list', 'chatgpt', 'gpt4',...",Curated list of chatgpt prompts from the top-r...,4.817416,1.0,1.0,9.231098,148.0
23,7dbc56bf-b0c5-5b88-a171-3f676b61191a,youngwookim/awesome-hadoop,[],A curated list of amazingly awesome Hadoop and...,5.397048,1.0,1.0,9.277819,172.0
24,e2abc867-298f-5ee6-bb47-4a200494aab7,pawl/awesome-etl,[],"A curated list of awesome ETL frameworks, libr...",5.372819,1.0,1.0,9.535966,69.0
18,bb89d0c8-db30-5379-9b8d-f4b0f5dd3a4f,brianspiering/awesome-deep-rl,[],A curated list of awesome Deep Reinforcement L...,5.733269,1.0,1.0,9.535966,64.0
12,f283f1aa-2254-5605-9630-80c59c07024b,ramitsurana/awesome-kubernetes,"['aws', 'azure', 'books', 'cloud-providers', '...",A curated list for awesome kubernetes sources ...,6.136012,1.0,1.0,9.535966,110.0
17,551634f3-7fc6-5b31-a676-b693e59d648c,theanalyst/awesome-distributed-systems,"['architecture', 'consensus', 'distributed-sys...",A curated list to learn about distributed systems,5.804758,1.0,1.0,9.576292,107.0
20,4060f165-6902-53bc-8e6d-60217fda3ea2,costezki/awesome-nlprojects,"['awersome-list', 'machine-learning', 'natural...",List of projects related to Natural Language P...,5.597083,1.0,1.0,9.620706,128.0
28,3691b379-d8b0-53b9-9375-a95dfb68a5ad,n2cholas/awesome-jax,"['autograd', 'awesome', 'awesome-list', 'deep-...",JAX - A curated list of resources https://gith...,5.104913,1.0,1.0,9.755164,394.0
16,42af1a59-3545-55cf-a2f8-6165e4edf4ec,pabloem/awesome-beam,[],A curated list of awesome resources for Apache...,5.834331,1.0,1.0,9.823368,42.0
15,5bab555b-9ee4-500e-8f8a-738d2247825b,mauhai/awesome-jupyterlab,"['awesome', 'collections', 'jupyterlab', 'jupy...",A curated list of awesome JupyterLab extension...,5.893960,1.0,1.0,9.823368,53.0
19,8ca301dc-cd7d-5502-a5a8-4f9a88db7cad,Palashio/awesome-libra,[],A curated list of all things related to libra.,5.604686,1.0,1.0,10.145296,16.0
22,7fddb7a8-8ca3-56f4-bdcc-9088fd1315f0,travisvn/awesome-claude-skills,"['agentic-coding', 'anthropic', 'awesome', 'aw...","A curated list of awesome Claude Skills, resou...",5.435575,1.0,1.0,10.215125,57.0
69,3b441a31-8b40-5e98-b51b-9d3a374570a1,Engineer1999/A-Curated-List-of-ML-System-Desig...,[],This repository contains a curated collection ...,3.407397,1.0,1.0,10.222190,317.0
13,102480a9-60d3-56ee-b142-3573a3b9c9a8,visenger/awesome-mlops,"['ai', 'data-science', 'devops', 'engineering'...",A curated list of references for MLOps,6.003039,1.0,1.0,10.508368,528.0

In [72]:
comparison2.query('is_a_curated_list == 0').sort_values('score_v2', ascending=True)

,id,repo,topics,description,score_v1,is_a_curated_list,is_not_a_library,score_v2,url_count
202,e90fb75b-37dd-5f23-bca4-04faec7978f8,gorakhargosh/watchdog,[],Python library and shell utilities to monitor ...,1.027404,0.0,0.0,1.027404,32.0
201,28f5143a-7b06-5cb7-9831-dd5db52a39e6,devinpleuler/analytics-handbook,[],Getting started with soccer analytics,1.032347,0.0,0.0,1.032347,157.0
200,5bc0451b-6390-5127-9b10-a9dd003d0d63,h2oai/h2o-3,"['automl', 'big-data', 'data-science', 'deep-l...","H2O is an Open Source, Distributed, Fast & Sca...",1.064105,0.0,0.0,1.064105,114.0
199,4f55e95e-7ebd-5158-8006-968841169832,a8m/golang-cheat-sheet,"['cheat-sheets', 'cheatsheet', 'go', 'golang']",An overview of Go syntax and features.,1.071749,0.0,1.0,1.071749,6.0
196,463cc271-96c3-56a8-80c5-c1bca2a67cf3,cloneofsimo/lora,"['diffusion', 'dreambooth', 'fine-tuning', 'lo...",Using Low-rank adaptation to quickly fine-tune...,1.081852,0.0,0.0,1.081852,23.0
195,c825ba40-ed88-510a-9afd-ff2bcf71a6cf,pytorch/rl,"['ai', 'control', 'decision-making', 'distribu...","A modular, primitive-first, python-first PyTor...",1.095050,0.0,0.0,1.095050,107.0
194,db58c1c8-3f08-58df-b5f8-70b499d5ee5e,dbrattli/Expression,"['fsharp', 'functional-programming', 'oslash',...",Functional programming for Python,1.100268,0.0,0.0,1.100268,48.0
193,3a5e8997-f932-53b4-b3e6-8ca20d5671c6,jd/tenacity,"['failure', 'hacktoberfest', 'python', 'retry'...",Retrying library for Python,1.106836,0.0,0.0,1.106836,12.0
191,cfc97d5e-7a05-55a6-9d13-9c9f79390312,MilaNLProc/contextualized-topic-models,"['bert', 'embeddings', 'multilingual-models', ...",A python package to run contextualized topic m...,1.144430,0.0,0.0,1.144430,61.0
188,7199ac5d-6d13-5de2-82c6-6671f3805f7e,omkarcloud/botasaurus,"['anti-bot', 'anti-detect', 'anti-detect-brows...",The All in One Framework to Build Undefeatable...,1.159648,0.0,0.0,1.159648,231.0
186,7852046f-de3e-5e7d-98b4-2972477d0251,RecList/evalRS-CIKM-2022,[],Official Repository for EvalRS @ CIKM 2022: a ...,1.209891,0.0,0.0,1.209891,50.0
185,4f096931-89c7-566b-8d15-a67842e3f309,pyjanitor-devs/pyjanitor,"['cleaning-data', 'data', 'data-engineering', ...",Clean APIs for data cleaning. Python implement...,1.210655,0.0,0.0,1.210655,285.0
182,c8ee7b7a-28a6-59be-a05c-1397d9e4d28c,RecList/reclist,"['evaluation', 'machine-learning', 'machine-le...","Behavioral ""black-box"" testing for recommender...",1.243991,0.0,0.0,1.243991,59.0
180,e7f8ac3b-44d2-5db5-9a33-f76bd6dbb40f,ml-tooling/ml-workspace,"['anaconda', 'data-analysis', 'data-science', ...",🛠 All-in-one web-based IDE specialized for mac...,1.246864,0.0,0.0,1.246864,182.0
179,17b37b20-34f4-5200-8aea-170012d254e2,hiredscorelabs/cornell,"['mock', 'python', 'testing']",Cornell - record & replay mock server,1.257359,0.0,0.0,1.257359,27.0
178,2f5cd38a-430f-5ad3-8e69-3b3b028e733f,NVlabs/instant-ngp,"['3d-reconstruction', 'computer-graphics', 'co...",Instant neural graphics primitives: lightning ...,1.300227,0.0,0.0,1.300227,82.0
176,982f9dd8-ed3a-5701-b24b-5b2491a9293a,google/brax,"['jax', 'physics-simulation', 'reinforcement-l...",Massively parallel rigidbody physics simulatio...,1.345636,0.0,0.0,1.345636,37.0
175,219bb3eb-1ea0-5d51-a680-4e8ca7d19987,online-ml/river,"['concept-drift', 'data-science', 'incremental...",🌊 Online machine learning in Python,1.356843,0.0,0.0,1.356843,37.0
173,4a7338df-90c2-5135-a738-90222c251f81,NVIDIA-NeMo/Nemotron,[],Developer Asset Hub for NVIDIA Nemotron — A on...,1.370266,0.0,0.0,1.370266,88.0
172,21b51f09-819d-5167-82d6-74391bf20b4e,IDEA-Research/DINO,"['computer-vision', 'deep-learning', 'object-d...",[ICLR 2023] Official implementation of the pap...,1.371171,0.0,0.0,1.371171,88.0
171,dc6c5fe3-e47e-50ae-bbee-f87aea9b209b,rholder/retrying,[],Retrying is an Apache 2.0 licensed general-pur...,1.381778,0.0,0.0,1.381778,8.0
169,49492ad3-8399-5aee-a2c0-28d9f3332c1b,weaviate/weaviate,"['approximate-nearest-neighbor-search', 'gener...",Weaviate is an open-source vector database tha...,1.436227,0.0,1.0,1.436227,119.0
168,58028747-9e51-5ea8-9b50-dceef0790bd7,escobar-west/polars-cookbook,[],Recipes for using Python's polars library,1.439784,0.0,0.0,1.439784,21.0
167,f8480364-6e96-554f-ac63-4eefcba1489a,spandanb/learndb-py,['database'],Learn database internals by implementing it fr...,1.446174,0.0,0.0,1.446174,6.0
164,19b1eac4-f8ce-5ae2-8d5f-83cbe8e77edf,huggingface/datasets,"['ai', 'artificial-intelligence', 'computer-vi...",🤗 The largest hub of ready-to-use datasets for...,1.493097,0.0,0.0,1.493097,42.0
163,dfcbf78d-b2b1-54cb-8f13-1f2d92973c1e,wandb/weave,[],Weave is a toolkit for developing AI-powered a...,1.497119,0.0,0.0,1.497119,13.0
161,fa322b91-8b80-52c7-9544-056ad2d5ac39,httpie/cli,"['api', 'api-client', 'api-testing', 'cli', 'c...","🥧 HTTPie CLI — modern, user-friendly command-...",1.512173,0.0,0.0,1.512173,46.0
160,d2bb187f-3243-5f0a-8939-65dac80d0c13,huggingface/transformers,"['audio', 'deep-learning', 'deepseek', 'gemma'...",🤗 Transformers: the model-definition framework...,1.519193,0.0,0.0,1.519193,93.0
204,21203cf0-883b-553e-bd7e-53c0ac2af5c6,PaddlePaddle/PaddleSeg,"['autonomous-driving', 'human-segmentation', '...",Easy-to-use image segmentation library with aw...,1.013282,0.0,0.0,1.519922,39.0
158,605ead7c-d96f-5f56-b934-7306d366bf42,colohan/dschat,[],AppEngine hosted chat server. Example for the...,1.575545,0.0,1.0,1.575545,1.0
157,d462e32e-3cb2-5fc6-a563-5c800b14c53e,ShishirPatil/gorilla,"['api', 'api-documentation', 'chatgpt', 'claud...",Gorilla: Training and Evaluating LLMs for Func...,1.578295,0.0,0.0,1.578295,57.0
156,245209c6-1317-5b61-9916-708c7028ec1b,docker/buildx,[],Docker CLI plugin for extended build capabilit...,1.587581,0.0,0.0,1.587581,36.0
155,05f137f3-d046-5985-a26c-7952445ba792,encode/django-rest-framework,"['api', 'django', 'python', 'rest']",Web APIs for Django. 🎸,1.596984,0.0,0.0,1.596984,30.0
154,bda7363c-d90d-515f-b17d-e2f77cb4406e,deepseek-ai/DeepSeek-R1,[],NaN,1.597310,0.0,1.0,1.597310,42.0
197,dcc15535-6170-529d-ad58-57fcbfe1b4e0,tmbo/questionary,['hacktoberfest'],Python library to build pretty command line us...,1.072304,0.0,0.0,1.608455,31.0
149,c221a215-a12a-5121-8987-a44d1d4bac79,upgini/upgini,"['automated-feature-engineering', 'automl', 'a...",Data search & enrichment library for Machine L...,1.634596,0.0,0.0,1.634596,95.0
148,12fbfd92-1704-53c3-98d7-1c8753621fd7,ThreeDotsLabs/watermill,"['cqrs', 'event-driven', 'event-sourcing', 'ev...",Building event-driven applications the easy wa...,1.635578,0.0,0.0,1.635578,39.0
147,0ff767dd-bb45-5065-ae41-f96851f5befc,CamDavidsonPilon/Probabilistic-Programming-and...,"['bayesian-methods', 'data-science', 'jupyter-...","aka ""Bayesian Methods for Hackers"": An introdu...",1.653147,0.0,0.0,1.653147,92.0
146,52b661b1-9db4-5ef7-ab2a-8ccb09e07df3,dynamicwebpaige/thinking-in-data,"['data', 'data-science', 'datascience', 'machi...",A VS Code extension pack to help users visuali...,1.661391,0.0,0.0,1.661391,89.0
145,903e1e84-1409-5daf-b4f4-017c9323fe5e,maziarraissi/PetGPT,[],Train your own PetGPT at home!,1.687802,0.0,0.0,1.687802,11.0
143,b6625d8a-b8cd-5c63-a036-b0a26e6a8249,dabl/dabl,[],Data Analysis Baseline Library,1.718170,0.0,0.0,1.718170,10.0
142,ecfafdf4-76e1-567f-bbfc-e3f823eef3b7,holoviz/panel,"['bokeh', 'control-panels', 'dashboards', 'dat...",Panel: The powerful data exploration & web app...,1.718254,0.0,0.0,1.718254,110.0
140,005f096f-5f55-5e05-b99e-92d5ae394f67,ourownstory/neural_prophet,"['artificial-intelligence', 'autoregression', ...",NeuralProphet: A simple forecasting package,1.728775,0.0,0.0,1.728775,33.0
137,fb9fb06f-bb82-5977-9bbd-cdb361ce0e16,Giskard-AI/giskard-oss,"['agent-evaluation', 'ai-red-team', 'ai-securi...",🐢 Open-Source Evaluation & Testing library for...,1.742677,0.0,0.0,1.742677,27.0
133,56536055-c045-5402-8dc7-814970649f1c,narwhals-dev/narwhals,"['cudf', 'dask', 'duckdb', 'ibis', 'pandas', '...",Lightweight and extensible compatibility layer...,1.797237,0.0,0.0,1.797237,68.0
132,b18b44ce-c6d0-5661-9cc0-216e423f8b76,fastapi/full-stack-fastapi-template,"['backend', 'chakra-ui', 'docker', 'fastapi', ...","Full stack, modern web application template. U...",1.807235,0.0,0.0,1.807235,29.0
130,60361dab-7c04-50c7-98c1-ee8417e3bd3f,squeaky-pl/japronto,[],Screaming-fast Python 3.5+ HTTP toolkit integr...,1.848208,0.0,0.0,1.848208,18.0
129,03c1629f-9088-5483-b75d-3aad43a012bb,theskumar/python-dotenv,"['12-factor-app', 'configuration', 'devops-too...",Reads key-value pairs from a .env file and can...,1.862953,0.0,0.0,1.862954,18.0
128,32869b12-2deb-5c34-914b-c7306a817b84,kedro-org/kedro,"['experiment-tracking', 'hacktoberfest', 'kedr...",Kedro is a toolbox for production-ready data s...,1.867094,0.0,0.0,1.867094,59.0
181,5c3c84ca-fdf1-5df2-9454-02ef01e4e0b9,h5bp/Front-end-Developer-Interview-Questions,"['css-questions', 'front-end', 'html-questions...",A list of helpful front-end related questions ...,1.246318,0.0,1.0,1.869477,325.0
127,d384403d-587a-5ac1-b33b-fd93873a8d71,litements/s3sqlite,[],Query SQLite files in S3 using s3fs,1.873896,0.0,0.0,1.873896,19.0
126,3e758b25-5620-50fe-b803-33eaece567f6,Mathews-Tom/no-magic,[],Because `model.fit()` isn't an explanation,1.885893,0.0,0.0,1.885893,17.0
125,863f894d-48b7-5f55-b484-c060c12fbd9c,nikhilgarg28/delegate,[],Delegate your coding work to a team of agents,1.890188,0.0,0.0,1.890188,11.0
123,bdc2965b-750c-5de2-bf08-edc91192f893,deepklarity/jupyter-text2code,"['jupyter-notebook', 'machine-learning', 'pyth...",A proof-of-concept jupyter extension which con...,1.910183,0.0,0.0,1.910183,9.0
122,be503592-ac51-520c-b2b4-2fac09eefa51,argilla-io/argilla,"['active-learning', 'ai', 'annotation-tool', '...",Argilla is a collaboration tool for AI enginee...,1.913075,0.0,0.0,1.913075,41.0
121,a0a0a1a6-651b-5618-b627-719c60a073c5,kracekumar/python-typing-koans,"['koans', 'mypy', 'pep-484', 'python', 'python...",Python typing koans to learn type-hints in Pyt...,1.936930,0.0,0.0,1.936930,7.0
119,421fd1c8-289d-5408-b741-eaaf9d18389a,data-describe/data-describe,"['analysis', 'data-science', 'eda', 'explorato...",data⎰describe: Pythonic EDA Accelerator for Da...,1.974859,0.0,0.0,1.974859,14.0
118,c6292757-8af0-5497-ba47-7e1ad05e8612,kafischer/terminal-copilot,[],A smart terminal assistant that helps you find...,2.008977,0.0,0.0,2.008977,2.0
117,f7cc3288-0f5a-5b67-baed-ac51553dd89a,TheAtticusProject/cuad,"['bert', 'legal-nlp']",CUAD (NeurIPS 2021),2.019284,0.0,0.0,2.019284,8.0
115,2e732476-df9b-531c-8b31-8c35abfbea87,justmarkham/pycon-2016-tutorial,[],Machine Learning with Text in scikit-learn,2.056796,0.0,0.0,2.056796,37.0
114,8e0fa4db-4482-59f6-9850-446d47e15f7d,basetenlabs/truss,"['artificial-intelligence', 'easy-to-use', 'fa...",The simplest way to serve AI/ML models in prod...,2.056879,0.0,0.0,2.056879,24.0
189,a2557825-b667-5158-a0ce-31dac74ba58c,aden-hive/hive,"['agent', 'agent-framework', 'agent-skills', '...",Outcome driven agent development framework tha...,1.158318,0.0,0.0,2.064664,40.0
113,4a4b9161-3727-53ac-8847-314e317a55b0,sindresorhus/hyper-snazzy,"['color-scheme', 'hyper', 'hyper-theme', 'snaz...",Elegant Hyper theme with bright colors,2.070363,0.0,0.0,2.070363,26.0
112,609cadac-df5b-5ef4-a9d0-b6854d189bc1,saulpw/readysetdata,[],Scripts to make specific datasets cleaner and ...,2.090839,0.0,0.0,2.090839,17.0
111,1be9fcf2-9d78-5f31-b498-29213db6246a,catboost/catboost,"['big-data', 'catboost', 'categorical-features...","A fast, scalable, high performance Gradient Bo...",2.093503,0.0,0.0,2.093503,51.0
108,3d7beac1-1987-5bb9-bef1-4929bdc25f58,pemistahl/lingua-py,"['language-classification', 'language-detectio...",The most accurate natural language detection l...,2.130242,0.0,0.0,2.130242,46.0
106,02723175-538c-5fec-9a03-e4f5d3ae34fe,sktime/sktime,"['ai', 'anomaly-detection', 'changepoint-detec...",A unified framework for machine learning with ...,2.142525,0.0,0.0,2.142525,107.0
104,88faf490-333d-509f-a508-e122bb513e66,tensorflow/models,[],Models and examples built with TensorFlow,2.193957,0.0,1.0,2.193957,16.0
102,5553495e-5823-5810-9edc-c3af8d0ed816,muricoca/crab,[],"Crab is a ﬂexible, fast recommender engine for...",2.222141,0.0,0.0,2.222141,4.0
100,34967c25-97a2-5a9d-bc4e-c7ef8b14b41f,NVIDIA/NVFlare,"['decentralized', 'federated-analytics', 'fede...",NVIDIA Federated Learning Application Runtime ...,2.297491,0.0,0.0,2.297491,31.0
97,e21ba22c-477a-5587-9599-c51615cd8b71,ericmjl/essays-on-data-science,[],In which I put together my thoughts on the pra...,2.308947,0.0,1.0,2.308947,1.0
95,d87ea17e-c160-58a5-a6a7-72387cc57d4d,cookiecutter/cookiecutter-django,"['boilerplate', 'celery', 'cookiecutter', 'coo...",Cookiecutter Django is a framework for jumpsta...,2.340272,0.0,0.0,2.340272,74.0
94,3f1efa1e-13d5-5b24-a6eb-20671c337113,EthicalML/xai,"['ai', 'artificial-intelligence', 'bias', 'bia...",XAI - An eXplainability toolbox for machine le...,2.346099,0.0,0.0,2.346099,16.0
183,ee99a6e9-04ea-5d79-bbf7-3df4aaf86897,rwandaPinocle/Liszt,"['cards', 'kanban', 'liszt', 'note-taking', 'p...",A personal organization software with a script...,1.235824,0.0,0.0,2.471649,4.0
92,eca57cb7-5537-5df3-9f9a-07ac14397692,meltano/meltano,"['connectors', 'data', 'data-engineering', 'da...",Meltano: the declarative code-first data integ...,2.476568,0.0,1.0,2.476568,46.0
110,58bf86fd-2b9c-5216-9932-a9b516f2f926,google-deepmind/mujoco_menagerie,"['mujoco', 'robotics']",A collection of high-quality models for the Mu...,2.103555,0.0,1.0,2.599062,15.0
89,0fa1d7a6-b79e-5501-9906-cd4ac5425ec7,staringispolite/likeprogramming,[],Tired of being told how to talk to YOUR comput...,2.622923,0.0,1.0,2.622923,2.0
59,57b11bb5-de1d-571d-bc5e-7388e7164ba4,argoproj/argo-workflows,"['airflow', 'argo', 'argo-workflows', 'batch-p...",Workflow Engine for Kubernetes,3.780822,0.0,0.0,3.780822,72.0
124,78e0a572-c1d9-56d4-b638-b3f30564286d,grantjenks/python-sortedcontainers,"['data-types', 'dict', 'list', 'python', 'set'...","Python Sorted Container Types: Sorted List, So...",1.906544,0.0,0.0,3.813088,37.0
56,cf9d7b80-2462-5f4b-97aa-aafaf1fb7978,google-ai-edge/mediapipe,"['android', 'audio-processing', 'c-plus-plus',...","Cross-platform, customizable ML solutions for ...",3.895875,0.0,0.0,3.895875,49.0
53,3ecc67bd-75c1-565e-a61f-b962b1792f46,mattharrison/Tiny-Python-3.6-Notebook,[],This repository contains the text for the Tiny...,4.036488,0.0,1.0,4.036489,4.0
162,f46c2530-9e0f-58dd-aa3f-bca0f2cc06f7,ashishps1/awesome-behavioral-interviews,"['behavioral-interviews', 'interview-preparati...",Tips and resources to prepare for Behavioral i...,1.502413,0.0,1.0,4.098889,4.0
83,6511ca19-ae9c-5f68-8968-52edc028b32c,dennyzhang/cheatsheet-golang-A4,"['awesome', 'cheatsheet', 'denny-cheatsheets',...",:book: Advanced Golang Syntax In A4,2.811418,0.0,0.0,4.858891,202.0
120,e1598cb6-af1c-509c-b237-f19a9a8002cd,RamiKrispin/awesome-ds-setting,"['docker', 'git', 'python', 'rstats']",A tutorial for setting a new machine with core...,1.949177,0.0,1.0,4.924989,72.0
82,b7a3e428-be9c-5e9d-9097-86a5976160be,Westlake-AI/openmixup,"['automix', 'awesome-list', 'awesome-mim', 'aw...","CAIRI Supervised, Semi- and Self-Supervised Vi...",2.814956,0.0,0.0,4.950872,275.0
62,77913f3c-f6fe-58a4-8343-8e2965b354cf,faridrashidi/kaggle-solutions,"['awesome', 'competition', 'data-mining', 'dat...",🏅 Collection of Kaggle Solutions and Ideas 🏅,3.766013,0.0,1.0,5.373507,10.0
79,18730ec1-ade1-59d2-a99d-6af3815304ba,explosion/curated-transformers,"['albert', 'bert', 'camembert', 'dolly2', 'fal...",🤖 A PyTorch library of curated Transformer mod...,2.912382,0.0,0.0,8.260827,16.0

- having a URL count is another indicator of a curated list, not necessarily a legitimate repository that could be messing up results of user queries
- we utilize a BM25 scoring filter (IE `score_v2` boosting logic) stored on the index will be important for ignoring curated lists at retrieval time)
- 2nd filter on curated lists can be based on LLM as a judge (use an LLM to determine given all the data we have on the repo whether it is a curated list or not; can use a small LLM for this task so that it is fast)